import Link from "next/link";
import { notFound } from "next/navigation";
import { getPageById } from "@/services/pages/queries";
import { PageControls } from "@/components/pages/page-controls";
import { PublishDraftButton } from "@/components/pages/publish-draft-button";
import { PageTabs } from "@/components/pages/page-tabs";
import { getEnv } from "@/lib/env";

export const dynamic = "force-dynamic";
export default async function PageOverview({ params }: { params: Promise<{ pageId: string }> }) {
  const { pageId } = await params; const page = await getPageById(pageId); if (!page) notFound();
  const draft = page.configurationVersions.find((version) => version.status === "DRAFT"); const live = page.configurationVersions.find((version) => version.status === "LIVE"); const deepSeekConfigured = Boolean(getEnv().DEEPSEEK_API_KEY);
  return <main className="workspace"><div className="page-heading"><div><div className="eyebrow"><Link href="/pages">Pages</Link> / Overview</div><div className="page-ident"><div className="page-icon" style={{ width: 42, height: 42, fontSize: 16 }}>{page.name.charAt(0).toUpperCase()}</div><div><h1>{page.name}</h1><p className="subtitle" style={{ marginTop: 3 }}>Private Page workspace · {page.metaPageId ? `Meta ID ${page.metaPageId}` : "Meta connection pending"}</p></div></div></div><PageControls pageId={page.id} aiEnabled={page.aiEnabled} /></div>
    <div className="grid grid-4" style={{ marginBottom: 24 }}><Metric label="Facebook status" value={page.connectionStatus === "CONNECTED" ? "Connected" : "Not connected"} note="Meta Page connection" tone={page.connectionStatus === "CONNECTED" ? "green" : "gray"} /><Metric label="AI status" value={page.aiEnabled ? "Enabled" : "Paused"} note="Per-page control" tone={page.aiEnabled ? "green" : "gray"} /><Metric label="Business config" value={live ? "Live" : draft ? "Draft" : "Not started"} note={live ? `Version ${live.version}` : "Edit before publishing"} tone={live ? "green" : "gray"} /><Metric label="Products" value={String(page.products.length)} note="Active product catalog" tone="gray" /></div>
    <PageTabs pageId={page.id} active="Overview" />
    <div className="grid grid-2"><section className="card"><div className="section-head"><div><h2>Configuration lifecycle</h2><span className="muted">Draft changes never alter live behavior</span></div></div><div className="card-content"><div className="review-block"><h3>Draft configuration</h3><div className="card-footer" style={{ marginTop: 7 }}><span className="review-value">{draft ? `Version ${draft.version} · ${draft.label ?? "Unlabeled draft"}` : "No draft yet"}</span><span className="status-chip gray"><span className="dot" /> Draft</span></div></div><div className="review-block"><h3>Live configuration</h3><div className="card-footer" style={{ marginTop: 7 }}><span className="review-value">{live ? `Version ${live.version} · published ${live.publishedAt?.toLocaleDateString()}` : "Not published"}</span><span className={`status-chip ${live ? "green" : "gray"}`}><span className="dot" />{live ? "Live" : "Inactive"}</span></div></div><div style={{ display: "flex", gap: 9 }}><Link href={`/pages/${page.id}/business`} className="button secondary">Edit business setup</Link>{draft && <PublishDraftButton pageId={page.id} />}</div></div></section><section className="card"><div className="section-head"><div><h2>Connection state</h2><span className="muted">Operational status for this Page</span></div></div><div className="card-content"><Integration label="Facebook Messenger" status={page.connectionStatus === "CONNECTED" ? "Connected" : "Not connected"} tone={page.connectionStatus === "CONNECTED" ? "green" : "gray"} /><Integration label="Telegram" status={page.settings?.telegramEnabled ? "Enabled" : "Not configured"} tone={page.settings?.telegramEnabled ? "green" : "gray"} /><Integration label="DeepSeek" status={deepSeekConfigured ? "Configured" : "Not configured"} tone={deepSeekConfigured ? "green" : "gray"} /></div></section></div>
  </main>;
}
function Metric({ label, value, note, tone }: { label: string; value: string; note: string; tone: string }) { return <div className="card metric"><div className="metric-label">{label}</div><div className="metric-value" style={{ fontSize: 20 }}>{value}</div><div className={`status-chip ${tone}`} style={{ marginTop: 7 }}><span className="dot" />{note}</div></div>; }
function Integration({ label, status, tone }: { label: string; status: string; tone: string }) { return <div className="card-footer" style={{ padding: "5px 0 15px", borderBottom: "1px solid var(--line)" }}><span style={{ fontSize: 12, fontWeight: 650 }}>{label}</span><span className={`status-chip ${tone}`}><span className="dot" />{status}</span></div>; }
