import { notFound } from "next/navigation";
import { getPageById } from "@/services/pages/queries";
import { getPageUsage } from "@/services/usage/queries";
import { PageTabs } from "@/components/pages/page-tabs";

export const dynamic = "force-dynamic";
export default async function AiUsagePage({ params }: { params: Promise<{ pageId: string }> }) {
  const { pageId } = await params; const page = await getPageById(pageId); if (!page) notFound(); const usage = await getPageUsage(pageId);
  return <main className="workspace"><div className="page-heading"><div><div className="eyebrow">{page.name} / AI Usage</div><h1>AI usage</h1><p className="subtitle">Provider API usage for this Page only. Historical costs use stored rate snapshots.</p></div></div><PageTabs pageId={page.id} active="AI Usage" /><div className="grid grid-2"><UsageCard title="Today" summary={usage.today} /><UsageCard title="This month" summary={usage.month} /></div><section className="card" style={{ marginTop: 24 }}><div className="section-head"><div><h2>Daily usage</h2><span className="muted">Calls and token totals by UTC date</span></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Calls</th><th>Input tokens</th><th>Output tokens</th><th>Total tokens</th><th>Estimated cost</th></tr></thead><tbody>{usage.daily.map((row) => <tr key={row.date}><td>{row.date}</td><td>{row.calls}</td><td>{row.inputTokens}</td><td>{row.outputTokens}</td><td>{row.totalTokens}</td><td>{row.estimatedCost.toFixed(6)}</td></tr>)}</tbody></table>{usage.daily.length === 0 && <div className="empty-state"><h3>No AI usage yet</h3><p>Provider attempts will appear here once AI is configured and used.</p></div>}</div></section></main>;
}
function UsageCard({ title, summary }: { title: string; summary: { calls: number; inputTokens: number; outputTokens: number; totalTokens: number; estimatedCost: number } }) { return <section className="card card-pad"><div className="eyebrow">{title}</div><div className="grid grid-4" style={{ marginTop: 16 }}><Metric label="Calls" value={summary.calls} /><Metric label="Input" value={summary.inputTokens} /><Metric label="Output" value={summary.outputTokens} /><Metric label="Cost" value={summary.estimatedCost.toFixed(6)} /></div></section>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><div className="metric-label">{label}</div><div className="metric-value" style={{ fontSize: 20 }}>{value}</div></div>; }
