import { notFound, redirect } from "next/navigation";
import { getPageById } from "@/services/pages/queries";
import { getPageUsage } from "@/services/usage/queries";
import { PageTabs } from "@/components/pages/page-tabs";
import { PageBudgetControl } from "@/components/pages/page-budget-control";

export const dynamic = "force-dynamic";
export default async function AiUsagePage({ params }: { params: Promise<{ pageId: string }> }) {
  const { pageId } = await params; const page = await getPageById(pageId); if (!page) notFound(); if (pageId !== page.slug) redirect(`/pages/${page.slug}/usage`); const usage = await getPageUsage(page.id);
  return <main className="workspace"><div className="page-heading"><div><div className="eyebrow">{page.name} / AI Usage</div><h1>AI Usage</h1><p className="subtitle">Only this Page’s provider calls, tokens, balance and budget are shown here.</p></div></div><PageTabs pageId={page.slug} active="AI Usage" /><div className="grid grid-2"><UsageCard title="TODAY" summary={usage.today} /><UsageCard title="THIS MONTH" summary={usage.month} /></div><PageBudgetControl pageId={page.id} /><section className="card" style={{ marginTop: 24 }}><div className="section-head"><div><h2>Daily usage</h2><span className="muted">Calls and token totals by UTC date</span></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Calls</th><th>Input</th><th>Cached input</th><th>Output</th><th>USD</th><th>BDT</th></tr></thead><tbody>{usage.daily.map((row) => <tr key={row.date}><td>{row.date}</td><td>{row.calls}</td><td>{row.inputTokens.toLocaleString()}</td><td>{row.cachedInputTokens.toLocaleString()}</td><td>{row.outputTokens.toLocaleString()}</td><td>${row.estimatedCostUsd.toFixed(6)}</td><td>৳{row.estimatedCostBdt.toFixed(4)}</td></tr>)}</tbody></table>{usage.daily.length === 0 && <div className="empty-state"><h3>No AI usage yet</h3><p>Provider attempts will appear here once this Page is configured and used.</p></div>}</div></section></main>;
}
function UsageCard({ title, summary }: { title: string; summary: { calls: number; inputTokens: number; cachedInputTokens: number; outputTokens: number; estimatedCostUsd: number; estimatedCostBdt: number } }) { return <section className="card card-pad"><div className="eyebrow">{title}</div><div className="grid grid-3" style={{ marginTop: 16 }}><Metric label="Calls" value={summary.calls} /><Metric label="Input" value={summary.inputTokens} /><Metric label="Cached input" value={summary.cachedInputTokens} /><Metric label="Output" value={summary.outputTokens} /><Metric label="USD cost" value={`$${summary.estimatedCostUsd.toFixed(6)}`} /><Metric label="BDT cost" value={`৳${summary.estimatedCostBdt.toFixed(4)}`} /></div></section>; }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><div className="metric-label">{label}</div><div className="metric-value" style={{ fontSize: 18 }}>{value}</div></div>; }
