import type { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";

export type PreviewPage = Prisma.PageGetPayload<{ include: { settings: true; connection: true; businessProfile: true; products: { include: { variants: true } }; configurationVersions: true; _count: true } }>;
export type PreviewIssue = { id: string; pageId: string | null; type: string; status: "OPEN" | "ACKNOWLEDGED" | "RESOLVED"; severity: string; title: string; description: string | null; resolutionAction: string | null; createdAt: Date; updatedAt: Date; page: { id: string; name: string; metaPageId: string | null } | null };
export type PreviewOrder = { id: string; pageId: string; customerId: string; orderSessionId: string; status: string; total: number; payload: Record<string, unknown>; productId: string; productName: string; variantId: string; variantDetails: { sku: string; size: string | null; color?: string | null }; unitPrice: number; quantity: number; currency: string; customerName: string; normalizedPhone: string; phoneOriginal: string; fullAddress: string; configurationVersion: number; confirmedAt: Date; createdAt: Date; updatedAt: Date; revisions: unknown[] };
export type PreviewAiSettings = {
  language: "auto" | "bangla" | "banglish" | "english";
  tone: "natural_sales" | "friendly" | "formal" | "concise";
  replyLength: "short" | "medium";
  understandBeforeRecommend: boolean;
  avoidRepeatedQuestions: true;
  maxProductsPerRecommendation: 1 | 2;
  suggestCombo: boolean;
  askOneQuestionAtATime: boolean;
  mirrorCustomerLanguage: boolean;
  customerMemory: boolean;
  recentMessageContext: number;
  rollingSummary: boolean;
  smartBuffer: boolean;
  bufferWindowSeconds: number;
  manualCollisionProtection: boolean;
  manualActivityCooldownSeconds: number;
  staleReplyProtection: true;
  sequentialProcessing: true;
  customSalesInstructions: string;
  modelOverride?: "master" | "deepseek-v4-flash" | "deepseek-v4-pro";
  thinking?: "master" | "off" | "on";
  maxOutputTokens?: number;
};

export type PreviewPricing = { model: "deepseek-v4-flash" | "deepseek-v4-pro"; inputCacheHitUsd: number; inputCacheMissUsd: number; outputUsd: number; effectiveFrom: Date; updatedAt: Date };
export type PreviewControlCenter = {
  general: { applicationName: string; canonicalDomain: string; currency: "BDT"; timezone: string; country: string; language: string };
  meta: { appId: string; appSecretConfigured: boolean; verifyTokenConfigured: boolean; graphApiVersion: string; status: "NOT_CONFIGURED" | "READY" | "DEGRADED" | "ERROR"; lastError: string | null; lastTestAt: Date | null };
  ai: { provider: "DeepSeek"; apiKeyConfigured: boolean; baseUrl: string; defaultModel: "deepseek-v4-flash" | "deepseek-v4-pro"; thinkingMode: "off" | "on"; maxOutputTokens: number; timeoutMs: number; retryCount: number; status: "NOT_CONFIGURED" | "CONNECTED" | "LOW_BALANCE" | "NO_BALANCE" | "ERROR"; balanceUsd: number | null; balanceCny: number | null; lastBalanceAt: Date | null };
  telegram: { tokenConfigured: boolean; chatId: string; status: "NOT_CONFIGURED" | "CONNECTED" | "ERROR" };
  fx: { usdBdtRate: number; source: "MANUAL" | "AUTO"; updatedAt: Date };
  pricing: PreviewPricing[];
  globalBudget: { monthlyBdt: number | null; dailyBdt: number | null; hardLimit: boolean; warningThreshold: number; usedBdt: number; reservedBdt: number };
};

const defaultAiSettings: PreviewAiSettings = {
  language: "auto", tone: "natural_sales", replyLength: "short", understandBeforeRecommend: true,
  avoidRepeatedQuestions: true, maxProductsPerRecommendation: 1, suggestCombo: true,
  askOneQuestionAtATime: true, mirrorCustomerLanguage: true, customerMemory: true,
  recentMessageContext: 12, rollingSummary: true, smartBuffer: true, bufferWindowSeconds: 8,
  manualCollisionProtection: true, manualActivityCooldownSeconds: 30, staleReplyProtection: true,
  sequentialProcessing: true, customSalesInstructions: "",
};

const now = new Date("2026-01-15T10:00:00.000Z");
const PAGE_IDS = ["11111111-1111-4111-8111-111111111111", "11111111-1111-4111-8111-111111111112", "11111111-1111-4111-8111-111111111113"] as const;
type PageSeed = { id: string; metaPageId: string | null; name: string; slug: string; status: "CONNECTED" | "DISCONNECTED"; lifecycle: "LIVE" | "DRAFT"; business: string; description: string; currency: string; product: { id: string; name: string; description: string; sku: string; size: string; price: number; oldPrice: number; stockStatus: "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK" }; customer: { id: string; name: string; phone: string; address: string }; conversation: { id: string; lastMessage: string; status: "OPEN" | "CLOSED" }; usage: { today: [number, number, number, number, number]; month: [number, number, number, number, number]; daily: Array<[string, number, number, number, number]> } };
const seeds: PageSeed[] = [
  { id: PAGE_IDS[0], metaPageId: "105500000000001", name: "Growthifyx Demo Store", slug: "growthifyx-demo-store", status: "CONNECTED", lifecycle: "LIVE", business: "A practical personal-care shop with fast delivery and cash on delivery.", description: "Everyday hair and skin care products selected for simple routines.", currency: "USD", product: { id: "22222222-2222-4222-8222-222222222221", name: "Herbal Hair Repair Oil", description: "A lightweight daily care oil for dry, frizzy hair.", sku: "OIL-100", size: "100ml", price: 18, oldPrice: 22, stockStatus: "IN_STOCK" }, customer: { id: "44444444-4444-4444-8444-444444444441", name: "Maya Johnson", phone: "+15551234567", address: "123 Preview Street, Austin" }, conversation: { id: "55555555-5555-4555-8555-555555555551", lastMessage: "Can I order two bottles for delivery this week?", status: "OPEN" }, usage: { today: [4, 1080, 360, 1440, 0.0144], month: [18, 5240, 2110, 7350, 0.0735], daily: [["2026-01-13", 6, 1750, 690, 0.0244], ["2026-01-14", 8, 2410, 1060, 0.0347], ["2026-01-15", 4, 1080, 360, 0.0144]] } },
  { id: PAGE_IDS[1], metaPageId: "105500000000002", name: "Northstar Home Goods", slug: "northstar-home-goods", status: "CONNECTED", lifecycle: "DRAFT", business: "Warm, functional home goods for small apartments and thoughtful gifting.", description: "Compact organizers and home accessories with dependable delivery.", currency: "USD", product: { id: "22222222-2222-4222-8222-222222222222", name: "Cedar Desk Organizer", description: "A compact organizer with three compartments for a tidy workspace.", sku: "CEDAR-ORG", size: "Standard", price: 32, oldPrice: 38, stockStatus: "LOW_STOCK" }, customer: { id: "44444444-4444-4444-8444-444444444442", name: "Ethan Miller", phone: "+15559876543", address: "48 Market Lane, Denver" }, conversation: { id: "55555555-5555-4555-8555-555555555552", lastMessage: "Do you have the organizer in a darker finish?", status: "OPEN" }, usage: { today: [2, 460, 190, 650, 0.0065], month: [9, 2140, 820, 2960, 0.0296], daily: [["2026-01-14", 7, 1680, 630, 0.0231], ["2026-01-15", 2, 460, 190, 0.0065]] } },
  { id: PAGE_IDS[2], metaPageId: null, name: "Luna Wellness Studio", slug: "luna-wellness-studio", status: "DISCONNECTED", lifecycle: "DRAFT", business: "A calm wellness studio offering guided self-care kits and appointment support.", description: "A preview Page awaiting Facebook connection and business setup review.", currency: "USD", product: { id: "22222222-2222-4222-8222-222222222223", name: "Evening Reset Kit", description: "A gentle wind-down kit with herbal tea, a journal, and a sleep mask.", sku: "LUNA-RESET", size: "One size", price: 28, oldPrice: 34, stockStatus: "OUT_OF_STOCK" }, customer: { id: "44444444-4444-4444-8444-444444444443", name: "Sofia Chen", phone: "+15557654321", address: "9 Garden Avenue, Portland" }, conversation: { id: "55555555-5555-4555-8555-555555555553", lastMessage: "I would like to hear when the reset kit is available.", status: "CLOSED" }, usage: { today: [1, 180, 90, 270, 0.0027], month: [3, 510, 260, 770, 0.0077], daily: [["2026-01-15", 1, 180, 90, 0.0027]] } },
];

function makePage(seed: PageSeed): PreviewPage {
  const product = { id: seed.product.id, pageId: seed.id, name: seed.product.name, slug: seed.product.sku.toLowerCase(), description: seed.product.description, benefits: ["Thoughtfully selected", "Simple everyday use"], tags: ["preview", "featured"], active: true, createdAt: now, updatedAt: now, variants: [{ id: `${seed.product.id.slice(0, 8)}-variant`, productId: seed.product.id, sku: seed.product.sku, size: seed.product.size, color: null, currentPrice: seed.product.price, oldPrice: seed.product.oldPrice, stockStatus: seed.product.stockStatus, active: seed.product.stockStatus !== "OUT_OF_STOCK", createdAt: now, updatedAt: now }] };
  const profile = { id: randomUUID(), pageId: seed.id, businessName: seed.name, description: seed.description, benefits: ["Thoughtfully selected", "Simple everyday use"], deliveryPolicy: "Delivery within 3–5 business days.", codPolicy: "Cash on delivery is available.", faq: ["How long is delivery? 3–5 business days.", "Can I change my order? Contact the operator before dispatch."], policies: null, salesInstructions: "Never invent product facts or prices.", orderRequirements: ["name", "phone", "address"], notes: null, updatedAt: now, createdAt: now };
  const businessData = { business_profile: { business_name: seed.name, description: seed.description, benefits: profile.benefits }, products: [{ name: product.name, description: product.description, tags: product.tags, variants: [{ sku: seed.product.sku, size: seed.product.size, color: null, current_price: seed.product.price, old_price: seed.product.oldPrice }] }], policies: { delivery: profile.deliveryPolicy, cod: profile.codPolicy, faq: profile.faq }, sales_instructions: profile.salesInstructions, order_requirements: profile.orderRequirements, unknown_information: [], conflicts: [] };
  const configuration = { id: randomUUID(), pageId: seed.id, version: 1, status: seed.lifecycle === "LIVE" ? "LIVE" : "DRAFT", label: `${seed.name} ${seed.lifecycle === "LIVE" ? "live" : "draft"} configuration`, rawBusinessInfo: `${seed.name} — ${seed.business}`, businessData, conflicts: [], parseStatus: "READY", publishedAt: seed.lifecycle === "LIVE" ? now : null, createdAt: now };
  return { id: seed.id, metaPageId: seed.metaPageId, name: seed.name, slug: seed.slug, isActive: true, aiEnabled: seed.id !== PAGE_IDS[2], connectionStatus: seed.status, lifecycleStatus: seed.lifecycle, readinessCheckedAt: seed.lifecycle === "LIVE" ? now : null, createdAt: now, updatedAt: now, connection: { id: randomUUID(), pageId: seed.id, status: seed.status, provider: "meta", encryptedToken: seed.metaPageId ? "preview-only" : null, connectedAt: seed.metaPageId ? now : null, lastError: null, subscribedAt: seed.metaPageId ? now : null, lastHealthCheckAt: seed.metaPageId ? now : null, lastHealthCheckStatus: seed.metaPageId ? "healthy" : null, createdAt: now, updatedAt: now }, settings: { id: randomUUID(), pageId: seed.id, currency: seed.currency, countryCode: "US", defaultLanguage: "en", tone: "helpful", requiredOrderFields: ["name", "phone", "address", "product", "variant", "quantity"], globalAiPaused: false, telegramEnabled: false, encryptedTelegramBotToken: null, telegramChatId: null, createdAt: now, updatedAt: now }, businessProfile: profile, products: [product], configurationVersions: [configuration], _count: { customers: 1, conversations: 1, products: 1 } } as unknown as PreviewPage;
}

type PreviewPageBudget = { useMasterSettings: boolean; monthlyBdt: number | null; dailyBdt: number | null; hardLimit: boolean; warningThreshold: number; maxOutputTokens: number | null; modelOverride: "master" | "deepseek-v4-flash" | "deepseek-v4-pro"; pausedByBudget: boolean; reservedBdt: number };
type PreviewState = { pages: PreviewPage[]; globalAiPaused: boolean; aiSettings: Map<string, PreviewAiSettings>; pageBudgets: Map<string, PreviewPageBudget>; usage: Map<string, { calls: number; inputTokens: number; outputTokens: number; totalTokens: number; estimatedCost: number }>; issues: PreviewIssue[]; control: PreviewControlCenter };
const previewGlobal = globalThis as typeof globalThis & { __growthifyxPreviewState?: PreviewState };
const previewState: PreviewState = previewGlobal.__growthifyxPreviewState ?? { pages: seeds.map(makePage), globalAiPaused: false, aiSettings: new Map(), pageBudgets: new Map(), usage: new Map(), issues: [], control: { general: { applicationName: "Growthifyx AI Sales", canonicalDomain: "https://ai.growthifyx.space", currency: "BDT", timezone: "Asia/Dhaka", country: "Bangladesh", language: "Auto" }, meta: { appId: "", appSecretConfigured: false, verifyTokenConfigured: false, graphApiVersion: "v23.0", status: "NOT_CONFIGURED", lastError: null, lastTestAt: null }, ai: { provider: "DeepSeek", apiKeyConfigured: false, baseUrl: "https://api.deepseek.com", defaultModel: "deepseek-v4-flash", thinkingMode: "off", maxOutputTokens: 700, timeoutMs: 30000, retryCount: 1, status: "NOT_CONFIGURED", balanceUsd: null, balanceCny: null, lastBalanceAt: null }, telegram: { tokenConfigured: false, chatId: "", status: "NOT_CONFIGURED" }, fx: { usdBdtRate: 120, source: "MANUAL", updatedAt: now }, pricing: [{ model: "deepseek-v4-flash", inputCacheHitUsd: 0.1, inputCacheMissUsd: 0.3, outputUsd: 1.1, effectiveFrom: now, updatedAt: now }, { model: "deepseek-v4-pro", inputCacheHitUsd: 0.3, inputCacheMissUsd: 1.2, outputUsd: 4.5, effectiveFrom: now, updatedAt: now }], globalBudget: { monthlyBdt: null, dailyBdt: null, hardLimit: false, warningThreshold: 85, usedBdt: 0, reservedBdt: 0 } } };
previewGlobal.__growthifyxPreviewState = previewState;
let pages = previewState.pages;
let globalAiPaused = previewState.globalAiPaused;
const previewAiSettings = previewState.aiSettings;
const previewUsage = previewState.usage;
let issues: PreviewIssue[] = previewState.issues.length ? previewState.issues : [
  { id: "77777777-7777-4777-8777-777777777771", pageId: PAGE_IDS[1], type: "CONFIGURATION", status: "OPEN", severity: "medium", title: "Northstar draft has not been published", description: "The Page has a prepared catalog but its latest business configuration is still a draft.", resolutionAction: "Review the draft and publish it when ready.", createdAt: now, updatedAt: now, page: { id: PAGE_IDS[1], name: seeds[1].name, metaPageId: seeds[1].metaPageId } },
  { id: "77777777-7777-4777-8777-777777777772", pageId: PAGE_IDS[2], type: "META_CONNECTION", status: "OPEN", severity: "high", title: "Luna Wellness Studio is not connected", description: "Connect the Facebook Page before enabling live Messenger operations.", resolutionAction: "Reconnect the Facebook Page.", createdAt: now, updatedAt: now, page: { id: PAGE_IDS[2], name: seeds[2].name, metaPageId: null } },
  { id: "77777777-7777-4777-8777-777777777773", pageId: PAGE_IDS[0], type: "PREVIEW", status: "OPEN", severity: "low", title: "Development preview is active", description: "This data is local fixture data and is never used by production runtime.", resolutionAction: "Disable DEV_PREVIEW before production deployment.", createdAt: now, updatedAt: now, page: { id: PAGE_IDS[0], name: seeds[0].name, metaPageId: seeds[0].metaPageId } },
];
previewState.issues = issues;
export function persistPreviewState() { previewState.pages = pages; previewState.globalAiPaused = globalAiPaused; previewState.issues = issues; }
if (!previewState.pageBudgets) previewState.pageBudgets = new Map();
if (!previewState.control) throw new Error("Preview control center state is unavailable; restart preview mode.");
function pageKey(pageId: string) { const page = pageFor(pageId); return page.id; }
function pricingFor(model: "deepseek-v4-flash" | "deepseek-v4-pro") { return previewState.control.pricing.find((item) => item.model === model) ?? previewState.control.pricing[0]; }
export function getPreviewControlCenter(): PreviewControlCenter { const control = structuredClone(previewState.control); control.globalBudget.usedBdt = pages.reduce((total, page) => total + getPreviewUsage(page.id).month.estimatedCost * control.fx.usdBdtRate, 0); return control; }
export function updatePreviewMeta(input: { appId: string; appSecret?: string; verifyToken?: string; graphApiVersion?: string }) { const current = previewState.control.meta; previewState.control.meta = { ...current, appId: input.appId.trim(), appSecretConfigured: Boolean(input.appSecret?.trim()) || current.appSecretConfigured, verifyTokenConfigured: Boolean(input.verifyToken?.trim()) || current.verifyTokenConfigured, graphApiVersion: input.graphApiVersion?.trim() || current.graphApiVersion, status: input.appId.trim() && (Boolean(input.appSecret?.trim()) || current.appSecretConfigured) && (Boolean(input.verifyToken?.trim()) || current.verifyTokenConfigured) ? "READY" : "DEGRADED", lastError: null }; return getPreviewControlCenter().meta; }
export function testPreviewMeta() { previewState.control.meta = { ...previewState.control.meta, status: previewState.control.meta.appId && previewState.control.meta.appSecretConfigured ? "READY" : "ERROR", lastError: previewState.control.meta.appId && previewState.control.meta.appSecretConfigured ? null : "Configure the App ID and App Secret first.", lastTestAt: new Date() }; return getPreviewControlCenter().meta; }
export function updatePreviewAiProvider(input: { apiKey?: string; defaultModel?: "deepseek-v4-flash" | "deepseek-v4-pro"; thinkingMode?: "off" | "on"; maxOutputTokens?: number; timeoutMs?: number; retryCount?: number }) { const current = previewState.control.ai; previewState.control.ai = { ...current, apiKeyConfigured: Boolean(input.apiKey?.trim()) || current.apiKeyConfigured, defaultModel: input.defaultModel ?? current.defaultModel, thinkingMode: input.thinkingMode ?? current.thinkingMode, maxOutputTokens: input.maxOutputTokens ?? current.maxOutputTokens, timeoutMs: input.timeoutMs ?? current.timeoutMs, retryCount: input.retryCount ?? current.retryCount, status: Boolean(input.apiKey?.trim()) || current.apiKeyConfigured ? "CONNECTED" : "NOT_CONFIGURED" }; return getPreviewControlCenter().ai; }
export function refreshPreviewBalance() { const balanceUsd = 18.42; const balanceCny = 132.6; previewState.control.ai = { ...previewState.control.ai, balanceUsd, balanceCny, lastBalanceAt: new Date(), status: balanceUsd < 5 ? "LOW_BALANCE" : "CONNECTED" }; return getPreviewControlCenter().ai; }
export function updatePreviewTelegram(input: { token?: string; chatId: string }) { previewState.control.telegram = { ...previewState.control.telegram, tokenConfigured: Boolean(input.token?.trim()) || previewState.control.telegram.tokenConfigured, chatId: input.chatId.trim(), status: Boolean(input.token?.trim()) || previewState.control.telegram.tokenConfigured ? "CONNECTED" : "NOT_CONFIGURED" }; return getPreviewControlCenter().telegram; }
export function updatePreviewFxRate(rate: number) { if (!Number.isFinite(rate) || rate <= 0) throw new Error("FX rate must be greater than zero."); previewState.control.fx = { ...previewState.control.fx, usdBdtRate: rate, updatedAt: new Date() }; return getPreviewControlCenter().fx; }
export function updatePreviewPricing(input: { model: "deepseek-v4-flash" | "deepseek-v4-pro"; inputCacheHitUsd: number; inputCacheMissUsd: number; outputUsd: number }) { const current = previewState.control.pricing; previewState.control.pricing = current.map((item) => item.model === input.model ? { ...item, inputCacheHitUsd: input.inputCacheHitUsd, inputCacheMissUsd: input.inputCacheMissUsd, outputUsd: input.outputUsd, updatedAt: new Date() } : item); return getPreviewControlCenter().pricing; }
export function updatePreviewGlobalBudget(input: { monthlyBdt: number | null; dailyBdt: number | null; hardLimit: boolean; warningThreshold: number }) { previewState.control.globalBudget = { ...previewState.control.globalBudget, monthlyBdt: input.monthlyBdt, dailyBdt: input.dailyBdt, hardLimit: input.hardLimit, warningThreshold: input.warningThreshold }; return getPreviewControlCenter().globalBudget; }
function pageBudgetDefaults(): PreviewPageBudget { return { useMasterSettings: true, monthlyBdt: null, dailyBdt: null, hardLimit: false, warningThreshold: 85, maxOutputTokens: null, modelOverride: "master", pausedByBudget: false, reservedBdt: 0 }; }
export function getPreviewPageBudget(pageId: string) { const key = pageKey(pageId); return { ...pageBudgetDefaults(), ...(previewState.pageBudgets.get(key) ?? {}) }; }
export function getPreviewBudgetSummary(pageId: string) { const page = pageFor(pageId); const budget = getPreviewPageBudget(page.id); const usage = getPreviewUsage(page.id).month; const usedBdt = usage.estimatedCost * previewState.control.fx.usdBdtRate; return { ...budget, usedBdt, remainingBdt: budget.monthlyBdt === null ? null : Math.max(0, budget.monthlyBdt - usedBdt), state: budget.pausedByBudget ? "PAUSED_BY_BUDGET" : budget.monthlyBdt !== null && usedBdt >= budget.monthlyBdt ? "LIMIT_REACHED" : budget.monthlyBdt !== null && usedBdt >= budget.monthlyBdt * budget.warningThreshold / 100 ? "WARNING" : "HEALTHY", calls: usage.calls, inputTokens: usage.inputTokens, outputTokens: usage.outputTokens, estimatedUsd: usage.estimatedCost }; }
export function updatePreviewPageBudget(pageId: string, input: Partial<PreviewPageBudget>) { const key = pageKey(pageId); const next = { ...getPreviewPageBudget(key), ...input }; previewState.pageBudgets.set(key, next); if (next.monthlyBdt !== null && getPreviewBudgetSummary(key).usedBdt >= next.monthlyBdt && next.hardLimit) { next.pausedByBudget = true; setPreviewAi(false, key); createPreviewIssue({ pageId: key, type: "PAGE_BUDGET_LIMIT", title: `${pageFor(key).name} AI is paused by budget`, description: "The Page monthly AI budget has been reached. Incoming messages continue to be stored.", severity: "high", resolutionAction: "Increase the Page budget or resume AI." }); } persistPreviewState(); return getPreviewBudgetSummary(key); }
export function forcePreviewPageBudgetLimit(pageId: string) { const key = pageKey(pageId); const budget = getPreviewPageBudget(key); const usedBdt = getPreviewUsage(key).month.estimatedCost * previewState.control.fx.usdBdtRate; const next = { ...budget, monthlyBdt: Math.max(0.01, Math.min(budget.monthlyBdt ?? 999999, usedBdt || 0.01)), hardLimit: true, pausedByBudget: true }; previewState.pageBudgets.set(key, next); setPreviewAi(false, key); createPreviewIssue({ pageId: key, type: "PAGE_BUDGET_LIMIT", title: `${pageFor(key).name} AI is paused by budget`, description: "Preview simulation reached the Page hard limit.", severity: "high", resolutionAction: "Increase the Page budget or resume AI." }); persistPreviewState(); return getPreviewBudgetSummary(key); }
export function resumePreviewPageAi(pageId: string) { const key = pageKey(pageId); const budget = getPreviewPageBudget(key); previewState.pageBudgets.set(key, { ...budget, pausedByBudget: false }); setPreviewAi(true, key); persistPreviewState(); return getPreviewBudgetSummary(key); }
function pageFor(pageId?: string) { const page = pages.find((item) => item.id === pageId || item.slug === pageId); if (!page) throw new Error("Page not found"); return page; }
export function getPreviewFacebookPages() { return [{ id: "preview-meta-page-001", name: "Karseell Bangladesh" }, { id: "preview-meta-page-002", name: "Growthifyx Demo Store" }, { id: "preview-meta-page-003", name: "Demo Fashion" }]; }
export function getPreviewPages() { return pages; }
export function getPreviewPage(idOrSlug: string) { return pages.find((item) => item.id === idOrSlug || item.slug === idOrSlug) ?? null; }
export function getPreviewDashboard() { return { pages: pages.map((page) => { const usage = getPreviewUsage(page.id).month; return { id: page.id, slug: page.slug, name: page.name, connectionStatus: page.connectionStatus, aiEnabled: page.aiEnabled, usage: { calls: usage.calls, totalTokens: usage.totalTokens, estimatedCost: usage.estimatedCost, estimatedCostBdt: usage.estimatedCost * previewState.control.fx.usdBdtRate } }; }) }; }
export function connectPreviewPage(id: string, metaPageId: string, name: string) { const current = getPreviewPage(id); if (!current) return null; pages = pages.map((item) => item.id === id ? { ...item, name, metaPageId, connectionStatus: "CONNECTED", lifecycleStatus: "DRAFT", connection: { ...item.connection!, status: "CONNECTED", encryptedToken: "preview-only", connectedAt: new Date(), lastHealthCheckAt: new Date(), lastHealthCheckStatus: "healthy" } } as PreviewPage : item); persistPreviewState(); return getPreviewPage(id); }
export function createPreviewPage(name: string) { const id = randomUUID(); const base = makePage({ ...seeds[2], id, name, slug: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${id.slice(0, 8)}`, metaPageId: null }); pages = [...pages, base]; persistPreviewState(); return base; }
export function savePreviewBusiness(input: { pageId?: string; rawBusinessInfo: string; businessName?: string; description?: string; benefits?: string; deliveryPolicy?: string; codPolicy?: string; faq?: string; salesInstructions?: string; notes?: string }) { const current = pageFor(input.pageId); const version = Math.max(...current.configurationVersions.map((item) => item.version), 0) + 1; const previous = current.configurationVersions[0]; const draft = { ...previous, id: randomUUID(), version, status: "DRAFT", label: `Preview draft ${version}`, rawBusinessInfo: input.rawBusinessInfo, businessData: { ...(previous.businessData as object), business_profile: { business_name: input.businessName ?? null, description: input.description ?? null, benefits: (input.benefits ?? "").split("\n").filter(Boolean) }, policies: { delivery: input.deliveryPolicy ?? null, cod: input.codPolicy ?? null, faq: (input.faq ?? "").split("\n").filter(Boolean) }, sales_instructions: input.salesInstructions ?? null, order_requirements: (input.notes ?? "").split("\n").filter(Boolean), conflicts: [] }, parseStatus: "READY", publishedAt: null, createdAt: new Date() }; pages = pages.map((item) => item.id === current.id ? { ...item, configurationVersions: [draft, ...item.configurationVersions] } as PreviewPage : item); return draft; }
export function createPreviewProduct(input: { pageId?: string; name: string; description?: string; sku: string; price: number; oldPrice?: number; size?: string; color?: string }) { const current = pageFor(input.pageId); const productId = randomUUID(); const timestamp = new Date(); const product = { id: productId, pageId: current.id, name: input.name, slug: input.sku.toLowerCase(), description: input.description ?? null, benefits: [], tags: [], active: true, createdAt: timestamp, updatedAt: timestamp, variants: [{ id: randomUUID(), productId, sku: input.sku, size: input.size ?? null, color: input.color ?? null, currentPrice: input.price, oldPrice: input.oldPrice ?? null, stockStatus: "IN_STOCK", active: true, createdAt: timestamp, updatedAt: timestamp }] } as unknown as PreviewPage["products"][number]; const version = Math.max(...current.configurationVersions.map((item) => item.version), 0) + 1; const products = current.products.concat(product).map((item) => ({ name: item.name, description: item.description, tags: Array.isArray(item.tags) ? item.tags : [], variants: item.variants.map((variant) => ({ sku: variant.sku, size: variant.size, color: variant.color, current_price: Number(variant.currentPrice), old_price: variant.oldPrice === null ? null : Number(variant.oldPrice) })) })); const draft = { ...current.configurationVersions[0], id: randomUUID(), version, status: "DRAFT", label: `Catalog preview draft ${version}`, businessData: { ...(current.configurationVersions[0].businessData as object), products }, createdAt: timestamp, publishedAt: null }; pages = pages.map((item) => item.id === current.id ? { ...item, products: [...item.products, product], _count: { ...item._count, products: item.products.length + 1 }, configurationVersions: [draft, ...item.configurationVersions] } as PreviewPage : item); persistPreviewState(); return draft; }
export function updatePreviewProduct(input: { pageId: string; productId: string; name: string; description?: string; sku: string; price: number; oldPrice?: number; size?: string; color?: string; active?: boolean }) { const current = getPreviewPage(input.pageId); if (!current) throw new Error("Page not found"); const timestamp = new Date(); let updated: PreviewPage["products"][number] | null = null; const products = current.products.map((product) => { if (product.id !== input.productId) return product; updated = { ...product, name: input.name, description: input.description ?? null, active: input.active ?? product.active, updatedAt: timestamp, variants: product.variants.map((variant, index) => index === 0 ? { ...variant, sku: input.sku, currentPrice: input.price, oldPrice: input.oldPrice ?? null, size: input.size ?? null, color: input.color ?? null, updatedAt: timestamp } : variant) } as PreviewPage["products"][number]; return updated; }); if (!updated) throw new Error("Product not found"); pages = pages.map((item) => item.id === input.pageId ? { ...item, products } as PreviewPage : item); persistPreviewState(); return updated; }
export function setPreviewProductActive(pageId: string, productId: string, active: boolean) { const current = getPreviewPage(pageId); if (!current) throw new Error("Page not found"); pages = pages.map((item) => item.id === pageId ? { ...item, products: item.products.map((product) => product.id === productId ? { ...product, active, variants: product.variants.map((variant) => ({ ...variant, active })) } : product) } as PreviewPage : item); persistPreviewState(); return getPreviewPage(pageId); }
export function deletePreviewProduct(pageId: string, productId: string) { const current = getPreviewPage(pageId); if (!current) throw new Error("Page not found"); pages = pages.map((item) => item.id === pageId ? { ...item, products: item.products.filter((product) => product.id !== productId), _count: { ...item._count, products: Math.max(0, item.products.length - 1) } } as PreviewPage : item); persistPreviewState(); }
export function publishPreview(pageId: string) { const current = getPreviewPage(pageId); if (!current) throw new Error("Page not found"); const draft = current.configurationVersions.find((version) => version.status === "DRAFT"); if (!draft) throw new Error("No draft configuration to publish"); pages = pages.map((item) => item.id === pageId ? { ...item, lifecycleStatus: "LIVE", configurationVersions: item.configurationVersions.map((version) => ({ ...version, status: version.id === draft.id ? "LIVE" : version.status === "LIVE" ? "ARCHIVED" : version.status, publishedAt: version.id === draft.id ? new Date() : version.publishedAt })) } as PreviewPage : item); persistPreviewState(); return draft; }
export function rollbackPreview(pageId: string, version: number) { const current = getPreviewPage(pageId); const target = current?.configurationVersions.find((item) => item.version === version); if (!current || !target) throw new Error("Configuration version not found"); pages = pages.map((item) => item.id === pageId ? { ...item, configurationVersions: item.configurationVersions.map((versionItem) => ({ ...versionItem, status: versionItem.id === target.id ? "LIVE" : versionItem.status === "LIVE" ? "ARCHIVED" : versionItem.status })) } as PreviewPage : item); persistPreviewState(); return target; }
export function setPreviewAi(enabled: boolean, pageId?: string) { const current = pageId ? getPreviewPage(pageId) : pageFor(); if (!current) return null; pages = pages.map((item) => item.id === current.id ? { ...item, aiEnabled: enabled } as PreviewPage : item); persistPreviewState(); return pageFor(current.id); }
export function getPreviewAiSettings(pageId: string) { return previewAiSettings.get(pageId) ?? defaultAiSettings; }
export function updatePreviewAiSettings(pageId: string, input: Partial<PreviewAiSettings>) { const key = pageKey(pageId); const value = { ...getPreviewAiSettings(key), ...input, avoidRepeatedQuestions: true as const, staleReplyProtection: true as const, sequentialProcessing: true as const }; previewAiSettings.set(key, value); return value; }
export function runPreviewAiTest(pageId: string, message: string) { const page = getPreviewPage(pageId); if (!page) throw new Error("Page not found"); const configured = Boolean(process.env.DEEPSEEK_API_KEY) || previewState.control.ai.apiKeyConfigured; const product = page.products.find((item) => item.active && item.variants.some((variant) => variant.active)); const reply = configured ? `Provider test for ${page.name}: I can help with ${product?.name ?? "your products"}.` : `Mock reply for ${page.name}: I can help with ${product?.name ?? "our products"}. What would you like to know?`; const model = getPreviewAiSettings(page.id).modelOverride === "deepseek-v4-pro" ? "deepseek-v4-pro" : previewState.control.ai.defaultModel; const pricing = pricingFor(model); const estimatedUsd = 84 / 1_000_000 * pricing.inputCacheMissUsd + 34 / 1_000_000 * pricing.outputUsd; recordPreviewUsage(page.id, 84, 34, estimatedUsd); const summary = getPreviewBudgetSummary(page.id); const budget = getPreviewPageBudget(page.id); if (budget.hardLimit && summary.monthlyBdt !== null && summary.usedBdt >= summary.monthlyBdt && !budget.pausedByBudget) updatePreviewPageBudget(page.id, { pausedByBudget: true }); return { reply, label: configured ? "PREVIEW" : "MOCK", model, intent: message.toLowerCase().includes("price") ? "PRICE_INQUIRY" : "GENERAL_INQUIRY", factsExtracted: [], productsSelected: product ? [product.name] : [], questionKey: "customer_need", validationResult: "PASS", tokenUsage: { input: 84, output: 34, total: 118 }, estimatedUsd, estimatedBdt: estimatedUsd * previewState.control.fx.usdBdtRate, latencyMs: 42 }; }
export function setPreviewGlobalAi(paused: boolean) { globalAiPaused = paused; return paused; }
export function getPreviewGlobalAi() { return globalAiPaused; }
export function updatePreviewSettings(input: { pageId?: string; currency: string; countryCode: string; defaultLanguage: string; tone: string; requiredOrderFields: string[] }) { const current = pageFor(input.pageId); pages = pages.map((item) => item.id === current.id ? { ...item, settings: { ...item.settings!, ...input, updatedAt: new Date() } } as PreviewPage : item); return pageFor(current.id).settings; }
export function setPreviewLive(pageId?: string) { const current = pageId ? getPreviewPage(pageId) : pageFor(); if (!current) return null; pages = pages.map((item) => item.id === current.id ? { ...item, lifecycleStatus: "LIVE", aiEnabled: true, readinessCheckedAt: new Date() } as PreviewPage : item); persistPreviewState(); return pageFor(current.id); }
export function getPreviewIssues() { return issues.filter((issue) => issue.status !== "RESOLVED"); }
export function createPreviewIssue(input: { pageId?: string; type: string; title: string; description: string; severity?: string; resolutionAction?: string }) {
  const page = input.pageId ? getPreviewPage(input.pageId) : null;
  const issue: PreviewIssue = { id: randomUUID(), pageId: input.pageId ?? null, type: input.type, status: "OPEN", severity: input.severity ?? "medium", title: input.title, description: input.description, resolutionAction: input.resolutionAction ?? null, createdAt: new Date(), updatedAt: new Date(), page: page ? { id: page.id, name: page.name, metaPageId: page.metaPageId } : null };
  issues = [issue, ...issues];
  return issue;
}
export function resolvePreviewIssue(id: string) { issues = issues.map((issue) => issue.id === id ? { ...issue, status: "RESOLVED", updatedAt: new Date() } : issue); }
export function getPreviewOrders(pageId?: string): PreviewOrder[] { return pages.filter((item) => !pageId || item.id === pageId).map((page) => { const seed = seeds.find((item) => item.id === page.id) ?? seeds[0]; const quantity = page.id === PAGE_IDS[1] ? 1 : 2; return { id: `${page.id.slice(0, 8)}-order-0001`, pageId: page.id, customerId: seed.customer.id, orderSessionId: `${page.id.slice(0, 8)}-session-01`, status: page.id === PAGE_IDS[2] ? "CANCELLED" : "CONFIRMED", total: seed.product.price * quantity, payload: {}, productId: seed.product.id, productName: seed.product.name, variantId: `${seed.product.id.slice(0, 8)}-variant`, variantDetails: { sku: seed.product.sku, size: seed.product.size }, unitPrice: seed.product.price, quantity, currency: seed.currency, customerName: seed.customer.name, normalizedPhone: seed.customer.phone, phoneOriginal: seed.customer.phone, fullAddress: seed.customer.address, configurationVersion: 1, confirmedAt: now, createdAt: now, updatedAt: now, revisions: [] }; }); }
export function getPreviewConversations(pageId?: string) { return pages.filter((item) => !pageId || item.id === pageId).map((page) => { const seed = seeds.find((item) => item.id === page.id) ?? seeds[2]; return { id: seed.conversation.id, pageId: page.id, customerName: seed.customer.name, lastMessage: seed.conversation.lastMessage, status: seed.conversation.status, updatedAt: now }; }); }
export function getPreviewCustomers(pageId?: string) { return pages.filter((item) => !pageId || item.id === pageId).map((page) => { const seed = seeds.find((item) => item.id === page.id) ?? seeds[2]; return { id: seed.customer.id, pageId: page.id, name: seed.customer.name, phone: seed.customer.phone, orders: page.id === PAGE_IDS[2] ? 0 : 1, lastSeenAt: now }; }); }
export function recordPreviewUsage(pageId: string, inputTokens: number, outputTokens: number, estimatedCost: number) { const current = previewUsage.get(pageId) ?? { calls: 0, inputTokens: 0, outputTokens: 0, totalTokens: 0, estimatedCost: 0 }; previewUsage.set(pageId, { calls: current.calls + 1, inputTokens: current.inputTokens + inputTokens, outputTokens: current.outputTokens + outputTokens, totalTokens: current.totalTokens + inputTokens + outputTokens, estimatedCost: current.estimatedCost + estimatedCost }); }
export function getPreviewUsage(pageId?: string) { const seed = seeds.find((item) => item.id === pageId) ?? seeds[0]; const [todayCalls, todayInput, todayOutput, todayTotal, todayCost] = seed.usage.today; const [monthCalls, monthInput, monthOutput, monthTotal, monthCost] = seed.usage.month; const extra = previewUsage.get(pageId ?? seed.id); return { today: { calls: todayCalls + (extra?.calls ?? 0), inputTokens: todayInput + (extra?.inputTokens ?? 0), outputTokens: todayOutput + (extra?.outputTokens ?? 0), totalTokens: todayTotal + (extra?.totalTokens ?? 0), estimatedCost: todayCost + (extra?.estimatedCost ?? 0) }, month: { calls: monthCalls + (extra?.calls ?? 0), inputTokens: monthInput + (extra?.inputTokens ?? 0), outputTokens: monthOutput + (extra?.outputTokens ?? 0), totalTokens: monthTotal + (extra?.totalTokens ?? 0), estimatedCost: monthCost + (extra?.estimatedCost ?? 0) }, daily: seed.usage.daily.map(([date, calls, inputTokens, outputTokens, estimatedCost]) => ({ date, calls, inputTokens, outputTokens, totalTokens: inputTokens + outputTokens, estimatedCost })) }; }
