import { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";

export type PreviewPage = Prisma.PageGetPayload<{ include: { settings: true; connection: true; businessProfile: true; products: { include: { variants: true } }; configurationVersions: true; _count: true } }>;
export type PreviewIssue = { id: string; pageId: string | null; type: string; status: "OPEN" | "ACKNOWLEDGED" | "RESOLVED"; severity: string; title: string; description: string | null; resolutionAction: string | null; createdAt: Date; updatedAt: Date; page: { id: string; name: string; metaPageId: string | null } | null };

const PAGE_ID = "11111111-1111-4111-8111-111111111111";
const PRODUCT_ID = "22222222-2222-4222-8222-222222222222";
const VARIANT_ID = "33333333-3333-4333-8333-333333333333";
const CUSTOMER_ID = "44444444-4444-4444-8444-444444444444";
const CONVERSATION_ID = "55555555-5555-4555-8555-555555555555";
const CONFIG_ID = "66666666-6666-4666-8666-666666666666";
const now = new Date("2026-01-15T10:00:00.000Z");

function makePage(): PreviewPage {
  const product = { id: PRODUCT_ID, pageId: PAGE_ID, name: "Herbal Hair Repair Oil", slug: "herbal-hair-repair-oil", description: "A lightweight daily care oil for dry, frizzy hair.", benefits: ["Non-sticky", "Daily use"], tags: ["hair", "repair"], active: true, createdAt: now, updatedAt: now, variants: [{ id: VARIANT_ID, productId: PRODUCT_ID, sku: "OIL-100", size: "100ml", color: null, currentPrice: 18, oldPrice: 22, stockStatus: "IN_STOCK", active: true, createdAt: now, updatedAt: now }] } as unknown as PreviewPage["products"][number];
  return { id: PAGE_ID, metaPageId: "preview-meta-page-001", name: "Growthifyx Demo Page", slug: "growthifyx-demo-page", isActive: true, aiEnabled: true, connectionStatus: "CONNECTED", lifecycleStatus: "LIVE", readinessCheckedAt: now, createdAt: now, updatedAt: now, connection: { id: randomUUID(), pageId: PAGE_ID, status: "CONNECTED", provider: "meta", encryptedToken: "preview-only", connectedAt: now, lastError: null, subscribedAt: now, lastHealthCheckAt: now, lastHealthCheckStatus: "healthy", createdAt: now, updatedAt: now }, settings: { id: randomUUID(), pageId: PAGE_ID, currency: "USD", countryCode: "US", defaultLanguage: "en", tone: "helpful", requiredOrderFields: ["name", "phone", "address", "product", "variant", "quantity"], globalAiPaused: false, telegramEnabled: false, encryptedTelegramBotToken: null, telegramChatId: null, createdAt: now, updatedAt: now }, businessProfile: { id: randomUUID(), pageId: PAGE_ID, businessName: "Growthifyx Demo Store", description: "A local preview business profile.", benefits: ["Fast delivery", "Simple returns"], deliveryPolicy: "Delivery within 3–5 business days.", codPolicy: "Cash on delivery is available.", faq: ["How long is delivery? 3–5 business days."], policies: null, salesInstructions: "Never invent product facts or prices.", orderRequirements: ["name", "phone", "address"], notes: null, updatedAt: now, createdAt: now }, products: [product], configurationVersions: [{ id: CONFIG_ID, pageId: PAGE_ID, version: 1, status: "LIVE", label: "Preview live configuration", rawBusinessInfo: "Growthifyx Demo Store sells practical personal-care products with delivery and cash on delivery.", businessData: { business_profile: { business_name: "Growthifyx Demo Store", description: "A local preview business profile.", benefits: ["Fast delivery", "Simple returns"] }, products: [{ name: product.name, description: product.description, tags: product.tags, variants: [{ sku: "OIL-100", size: "100ml", color: null, current_price: 18, old_price: 22 }] }], policies: { delivery: "Delivery within 3–5 business days.", cod: "Cash on delivery is available.", faq: ["How long is delivery? 3–5 business days."] }, sales_instructions: "Never invent product facts or prices.", order_requirements: ["name", "phone", "address"], unknown_information: [], conflicts: [] }, conflicts: [], parseStatus: "READY", publishedAt: now, createdAt: now }], _count: { customers: 1, conversations: 1, products: 1 } } as unknown as PreviewPage;
}

let page = makePage();
let globalAiPaused = false;
let issues: PreviewIssue[] = [{ id: "77777777-7777-4777-8777-777777777777", pageId: PAGE_ID, type: "PREVIEW", status: "OPEN", severity: "low", title: "Development preview is active", description: "This data is local fixture data and is never used by production runtime.", resolutionAction: "Disable DEV_PREVIEW before production deployment.", createdAt: now, updatedAt: now, page: { id: PAGE_ID, name: page.name, metaPageId: page.metaPageId } }];

export function getPreviewPages() { return [page]; }
export function getPreviewPage(id: string) { return id === page.id ? page : null; }
export function getPreviewDashboard() { return { pages: [{ id: page.id, name: page.name, connectionStatus: page.connectionStatus, aiEnabled: page.aiEnabled, usage: { calls: 3, totalTokens: 1240, estimatedCost: 0.0124 } }] }; }
export function connectPreviewPage(id: string, metaPageId: string, name: string) { if (id === page.id) page = { ...page, name, metaPageId, connectionStatus: "CONNECTED", lifecycleStatus: "DRAFT", connection: { ...page.connection!, status: "CONNECTED", connectedAt: new Date() } }; return page; }
export function createPreviewPage(name: string) { page = { ...makePage(), id: PAGE_ID, name, metaPageId: null, slug: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-preview`, connectionStatus: "DISCONNECTED", lifecycleStatus: "DRAFT", connection: { ...makePage().connection!, pageId: PAGE_ID, status: "DISCONNECTED", encryptedToken: null, connectedAt: null } }; return page; }
export function savePreviewBusiness(input: { rawBusinessInfo: string; businessName?: string; description?: string; benefits?: string; deliveryPolicy?: string; codPolicy?: string; faq?: string; salesInstructions?: string; notes?: string }) { const version = Math.max(...page.configurationVersions.map((item) => item.version), 0) + 1; const draft = { ...page.configurationVersions[0], id: randomUUID(), version, status: "DRAFT", label: `Preview draft ${version}`, rawBusinessInfo: input.rawBusinessInfo, businessData: { business_profile: { business_name: input.businessName ?? null, description: input.description ?? null, benefits: (input.benefits ?? "").split("\n").filter(Boolean) }, products: page.products.map((product) => ({ name: product.name, description: product.description, tags: Array.isArray(product.tags) ? product.tags : [], variants: product.variants.map((variant) => ({ sku: variant.sku, size: variant.size, color: variant.color, current_price: Number(variant.currentPrice), old_price: variant.oldPrice === null ? null : Number(variant.oldPrice) })) })), policies: { delivery: input.deliveryPolicy ?? null, cod: input.codPolicy ?? null, faq: (input.faq ?? "").split("\n").filter(Boolean) }, sales_instructions: input.salesInstructions ?? null, order_requirements: (input.notes ?? "").split("\n").filter(Boolean), conflicts: [] }, parseStatus: "READY", publishedAt: null, createdAt: new Date() }; page = { ...page, configurationVersions: [draft, ...page.configurationVersions] } as PreviewPage; return draft; }
export function createPreviewProduct(input: { name: string; description?: string; sku: string; price: number; oldPrice?: number; size?: string; color?: string }) { const version = Math.max(...page.configurationVersions.map((item) => item.version), 0) + 1; const products = page.products.map((product) => ({ name: product.name, description: product.description, tags: Array.isArray(product.tags) ? product.tags : [], variants: product.variants.map((variant) => ({ sku: variant.sku, size: variant.size, color: variant.color, current_price: Number(variant.currentPrice), old_price: variant.oldPrice === null ? null : Number(variant.oldPrice) })) })); products.push({ name: input.name, description: input.description ?? null, tags: [], variants: [{ sku: input.sku, size: input.size ?? null, color: input.color ?? null, current_price: input.price, old_price: input.oldPrice ?? null }] }); const draft = { ...page.configurationVersions[0], id: randomUUID(), version, status: "DRAFT", label: `Catalog preview draft ${version}`, businessData: { ...(page.configurationVersions[0].businessData as object), products }, createdAt: new Date(), publishedAt: null }; page = { ...page, configurationVersions: [draft, ...page.configurationVersions] } as PreviewPage; return draft; }
export function publishPreview(pageId: string) { if (pageId !== page.id) throw new Error("Page not found"); const draft = page.configurationVersions.find((item) => item.status === "DRAFT"); if (!draft) throw new Error("No draft configuration to publish"); page = { ...page, lifecycleStatus: "LIVE", configurationVersions: page.configurationVersions.map((item) => ({ ...item, status: item.id === draft.id ? "LIVE" : item.status === "LIVE" ? "ARCHIVED" : item.status, publishedAt: item.id === draft.id ? new Date() : item.publishedAt })) } as PreviewPage; return draft; }
export function rollbackPreview(pageId: string, version: number) { const target = page.configurationVersions.find((item) => item.version === version); if (pageId !== page.id || !target) throw new Error("Configuration version not found"); page = { ...page, configurationVersions: page.configurationVersions.map((item) => ({ ...item, status: item.id === target.id ? "LIVE" : item.status === "LIVE" ? "ARCHIVED" : item.status })) } as PreviewPage; return target; }
export function setPreviewAi(enabled: boolean) { page = { ...page, aiEnabled: enabled }; return page; }
export function setPreviewGlobalAi(paused: boolean) { globalAiPaused = paused; return paused; }
export function getPreviewGlobalAi() { return globalAiPaused; }
export function updatePreviewSettings(input: { currency: string; countryCode: string; defaultLanguage: string; tone: string; requiredOrderFields: string[] }) { page = { ...page, settings: { ...page.settings!, ...input, updatedAt: new Date() } } as PreviewPage; return page.settings; }
export function setPreviewLive() { page = { ...page, lifecycleStatus: "LIVE", readinessCheckedAt: new Date() }; return page; }
export function getPreviewIssues() { return issues.filter((issue) => issue.status !== "RESOLVED"); }
export function resolvePreviewIssue(id: string) { issues = issues.map((issue) => issue.id === id ? { ...issue, status: "RESOLVED", updatedAt: new Date() } : issue); }
export function getPreviewOrders() { return [{ id: "88888888-8888-4888-8888-888888888888", pageId: page.id, customerId: "99999999-9999-4999-8999-999999999999", orderSessionId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", status: "CONFIRMED", total: 36, payload: {}, productId: PRODUCT_ID, productName: "Herbal Hair Repair Oil", variantId: VARIANT_ID, variantDetails: { sku: "OIL-100", size: "100ml" }, unitPrice: 18, quantity: 2, currency: "USD", customerName: "Preview Customer", normalizedPhone: "+15551234567", phoneOriginal: "5551234567", fullAddress: "123 Preview Street", configurationVersion: 1, confirmedAt: now, createdAt: now, updatedAt: now, revisions: [] }]; }
export function getPreviewConversations() { return [{ id: CONVERSATION_ID, pageId: page.id, customerName: "Preview Customer", lastMessage: "Can I order two bottles?", status: "OPEN", updatedAt: now }]; }
export function getPreviewCustomers() { return [{ id: CUSTOMER_ID, pageId: page.id, name: "Preview Customer", phone: "+15551234567", orders: 1, lastSeenAt: now }]; }
export function getPreviewUsage() { return { today: { calls: 2, inputTokens: 640, outputTokens: 210, totalTokens: 850, estimatedCost: 0.0085 }, month: { calls: 3, inputTokens: 910, outputTokens: 330, totalTokens: 1240, estimatedCost: 0.0124 }, daily: [{ date: "2026-01-15", calls: 3, inputTokens: 910, outputTokens: 330, totalTokens: 1240, estimatedCost: 0.0124 }] }; }
