import type { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";

export type PreviewPage = Prisma.PageGetPayload<{ include: { settings: true; connection: true; businessProfile: true; products: { include: { variants: true } }; configurationVersions: true; _count: true } }>;
export type PreviewIssue = { id: string; pageId: string | null; type: string; status: "OPEN" | "ACKNOWLEDGED" | "RESOLVED"; severity: string; title: string; description: string | null; resolutionAction: string | null; createdAt: Date; updatedAt: Date; page: { id: string; name: string; metaPageId: string | null } | null };
export type PreviewOrder = { id: string; pageId: string; customerId: string; orderSessionId: string; status: string; total: number; payload: Record<string, unknown>; productId: string; productName: string; variantId: string; variantDetails: { sku: string; size: string | null; color?: string | null }; unitPrice: number; quantity: number; currency: string; customerName: string; normalizedPhone: string; phoneOriginal: string; fullAddress: string; configurationVersion: number; confirmedAt: Date; createdAt: Date; updatedAt: Date; revisions: unknown[] };
export type PreviewAiSettings = {
  provider: "deepseek";
  apiKeyConfigured: boolean;
  accountLabel: string;
  providerStatus: "NOT_CONFIGURED" | "CONNECTED" | "ERROR";
  providerBalanceUsd: number | null;
  providerBalanceCny: number | null;
  lastBalanceAt: Date | null;
  language: "auto" | "bangla" | "banglish" | "english";
  tone: "natural_sales" | "friendly" | "formal" | "concise";
  replyLength: "short" | "medium";
  understandBeforeRecommend: boolean;
  avoidRepeatedQuestions: true;
  maxProductsPerRecommendation: 1 | 2;
  suggestCombo: boolean;
  askOneQuestionAtATime: boolean;
  mirrorCustomerLanguage: boolean;
  customerMemory: boolean;
  recentMessageContext: number;
  rollingSummary: boolean;
  smartBuffer: boolean;
  bufferWindowSeconds: number;
  manualCollisionProtection: boolean;
  manualActivityCooldownSeconds: number;
  staleReplyProtection: true;
  sequentialProcessing: true;
  customSalesInstructions: string;
  modelOverride?: "master" | "deepseek-v4-flash" | "deepseek-v4-pro";
  thinking?: "master" | "off" | "on";
  maxOutputTokens?: number;
};

export type PreviewPricing = { model: "deepseek-v4-flash" | "deepseek-v4-pro"; inputCacheHitUsd: number; inputCacheMissUsd: number; outputUsd: number; effectiveFrom: Date; updatedAt: Date };
export type PreviewTelegramSettings = { tokenConfigured: boolean; accountLabel: string; chatId: string; newOrderEnabled: boolean; updatedOrderEnabled: boolean; cancelledOrderEnabled: boolean; status: "NOT_CONFIGURED" | "CONNECTED" | "ERROR"; lastTestAt: Date | null };
export type PreviewMemoryFact = { id: string; pageId: string; customerId: string; factKey: string; normalizedValue: unknown; displayValue: string | null; sourceType: string; status: "ACTIVE" | "SUPERSEDED" | "REJECTED" | "UNCONFIRMED"; lastConfirmedAt: Date | null; updatedAt: Date; supersededByFactId?: string | null };
export type PreviewCustomerMemory = { pageId: string; customerId: string; memory: { knownFacts: Record<string, unknown>; unconfirmedFacts: Record<string, unknown>; needs: string[]; preferences: Record<string, unknown>; semanticQuestionsAsked: string[]; recommendedProductIds: string[]; rejectedProductIds: string[]; activeOrderReference: string | null; summary: string }; facts: PreviewMemoryFact[]; summaryStale: boolean; summaryVersion: number };
export type PreviewControlCenter = {
  [key: string]: unknown;
  globalAiPaused: boolean;
  general: { applicationName: string; canonicalDomain: string; currency: "BDT"; timezone: string; country: string; language: string };
  meta: { appId: string; appSecretConfigured: boolean; verifyTokenConfigured: boolean; graphApiVersion: string; loginConfigurationId?: string; loginConfigurationConfigured?: boolean; oauthRedirectUri?: string; oauthRedirectConfigured?: boolean; requiredPermissions?: string[]; status: "NOT_CONFIGURED" | "READY" | "DEGRADED" | "ERROR"; lastError: string | null; lastTestAt: Date | null };
};

const defaultAiSettings: PreviewAiSettings = {
  provider: "deepseek", apiKeyConfigured: false, accountLabel: "Not configured", providerStatus: "NOT_CONFIGURED", providerBalanceUsd: null, providerBalanceCny: null, lastBalanceAt: null,
  language: "auto", tone: "natural_sales", replyLength: "short", understandBeforeRecommend: true,
  avoidRepeatedQuestions: true, maxProductsPerRecommendation: 1, suggestCombo: true,
  askOneQuestionAtATime: true, mirrorCustomerLanguage: true, customerMemory: true,
  recentMessageContext: 12, rollingSummary: true, smartBuffer: true, bufferWindowSeconds: 8,
  manualCollisionProtection: true, manualActivityCooldownSeconds: 30, staleReplyProtection: true,
  sequentialProcessing: true, customSalesInstructions: "",
};

const now = new Date("2026-01-15T10:00:00.000Z");
const PAGE_IDS = ["11111111-1111-4111-8111-111111111111", "11111111-1111-4111-8111-111111111112", "11111111-1111-4111-8111-111111111113"] as const;
type PageSeed = { id: string; metaPageId: string | null; name: string; slug: string; status: "CONNECTED" | "DISCONNECTED"; lifecycle: "LIVE" | "DRAFT"; business: string; description: string; currency: string; product: { id: string; name: string; description: string; sku: string; size: string; price: number; oldPrice: number; stockStatus: "IN_STOCK" | "LOW_STOCK" | "OUT_OF_STOCK" }; customer: { id: string; name: string; phone: string; address: string }; conversation: { id: string; lastMessage: string; status: "OPEN" | "CLOSED" }; usage: { today: [number, number, number, number, number]; month: [number, number, number, number, number]; daily: Array<[string, number, number, number, number]> } };
const seeds: PageSeed[] = [
  { id: PAGE_IDS[0], metaPageId: "105500000000001", name: "Karseell Bangladesh", slug: "karseell-bangladesh", status: "CONNECTED", lifecycle: "LIVE", business: "Karseell personal-care products with fast delivery and cash on delivery.", description: "A page-scoped preview account for Karseell Bangladesh.", currency: "BDT", product: { id: "22222222-2222-4222-8222-222222222221", name: "Herbal Hair Repair Oil", description: "A lightweight daily care oil for dry, frizzy hair.", sku: "OIL-100", size: "100ml", price: 1800, oldPrice: 2200, stockStatus: "IN_STOCK" }, customer: { id: "44444444-4444-4444-8444-444444444441", name: "Maya Johnson", phone: "+15551234567", address: "123 Preview Street, Austin" }, conversation: { id: "55555555-5555-4555-8555-555555555551", lastMessage: "Can I order two bottles for delivery this week?", status: "OPEN" }, usage: { today: [4, 1080, 360, 1440, 0.0144], month: [18, 5240, 2110, 7350, 0.0735], daily: [["2026-01-13", 6, 1750, 690, 0.0244], ["2026-01-14", 8, 2410, 1060, 0.0347], ["2026-01-15", 4, 1080, 360, 0.0144]] } },
  { id: PAGE_IDS[1], metaPageId: "105500000000002", name: "Saree Page", slug: "saree-page", status: "CONNECTED", lifecycle: "DRAFT", business: "Saree Page fashion catalog with dependable delivery.", description: "A page-scoped preview account for Saree Page.", currency: "BDT", product: { id: "22222222-2222-4222-8222-222222222222", name: "Cedar Saree Collection", description: "A curated saree collection for gifting and everyday wear.", sku: "SAREE-ORG", size: "Standard", price: 3200, oldPrice: 3800, stockStatus: "LOW_STOCK" }, customer: { id: "44444444-4444-4444-8444-444444444442", name: "Ethan Miller", phone: "+15559876543", address: "48 Market Lane, Denver" }, conversation: { id: "55555555-5555-4555-8555-555555555552", lastMessage: "Do you have the saree in a darker finish?", status: "OPEN" }, usage: { today: [2, 460, 190, 650, 0.0065], month: [9, 2140, 820, 2960, 0.0296], daily: [["2026-01-14", 7, 1680, 630, 0.0231], ["2026-01-15", 2, 460, 190, 0.0065]] } },
  { id: PAGE_IDS[2], metaPageId: null, name: "Luna Wellness Studio", slug: "luna-wellness-studio", status: "DISCONNECTED", lifecycle: "DRAFT", business: "A calm wellness studio offering guided self-care kits and appointment support.", description: "A preview Page awaiting Facebook connection and business setup review.", currency: "USD", product: { id: "22222222-2222-4222-8222-222222222223", name: "Evening Reset Kit", description: "A gentle wind-down kit with herbal tea, a journal, and a sleep mask.", sku: "LUNA-RESET", size: "One size", price: 28, oldPrice: 34, stockStatus: "OUT_OF_STOCK" }, customer: { id: "44444444-4444-4444-8444-444444444443", name: "Sofia Chen", phone: "+15557654321", address: "9 Garden Avenue, Portland" }, conversation: { id: "55555555-5555-4555-8555-555555555553", lastMessage: "I would like to hear when the reset kit is available.", status: "CLOSED" }, usage: { today: [1, 180, 90, 270, 0.0027], month: [3, 510, 260, 770, 0.0077], daily: [["2026-01-15", 1, 180, 90, 0.0027]] } },
];

function makePage(seed: PageSeed): PreviewPage {
  const product = { id: seed.product.id, pageId: seed.id, name: seed.product.name, slug: seed.product.sku.toLowerCase(), description: seed.product.description, benefits: ["Thoughtfully selected", "Simple everyday use"], tags: ["preview", "featured"], active: true, createdAt: now, updatedAt: now, variants: [{ id: `${seed.product.id.slice(0, 8)}-variant`, productId: seed.product.id, sku: seed.product.sku, size: seed.product.size, color: null, currentPrice: seed.product.price, oldPrice: seed.product.oldPrice, stockStatus: seed.product.stockStatus, active: seed.product.stockStatus !== "OUT_OF_STOCK", createdAt: now, updatedAt: now }] };
  const profile = { id: randomUUID(), pageId: seed.id, businessName: seed.name, description: seed.description, benefits: ["Thoughtfully selected", "Simple everyday use"], deliveryPolicy: "Delivery within 3–5 business days.", codPolicy: "Cash on delivery is available.", faq: ["How long is delivery? 3–5 business days.", "Can I change my order? Contact the operator before dispatch."], policies: null, salesInstructions: "Never invent product facts or prices.", orderRequirements: ["name", "phone", "address"], notes: null, updatedAt: now, createdAt: now };
  const businessData = { business_profile: { business_name: seed.name, description: seed.description, benefits: profile.benefits }, products: [{ name: product.name, description: product.description, tags: product.tags, variants: [{ sku: seed.product.sku, size: seed.product.size, color: null, current_price: seed.product.price, old_price: seed.product.oldPrice }] }], policies: { delivery: profile.deliveryPolicy, cod: profile.codPolicy, faq: profile.faq }, sales_instructions: profile.salesInstructions, order_requirements: profile.orderRequirements, unknown_information: [], conflicts: [] };
  const configuration = { id: randomUUID(), pageId: seed.id, version: 1, status: seed.lifecycle === "LIVE" ? "LIVE" : "DRAFT", label: `${seed.name} ${seed.lifecycle === "LIVE" ? "live" : "draft"} configuration`, rawBusinessInfo: `${seed.name} — ${seed.business}`, businessData, conflicts: [], parseStatus: "READY", publishedAt: seed.lifecycle === "LIVE" ? now : null, createdAt: now };
  return { id: seed.id, metaPageId: seed.metaPageId, name: seed.name, slug: seed.slug, isActive: true, aiEnabled: seed.id !== PAGE_IDS[2], aiStatus: seed.id === PAGE_IDS[2] ? "PAUSED" : "RUNNING", connectionStatus: seed.status, lifecycleStatus: seed.lifecycle, readinessCheckedAt: seed.lifecycle === "LIVE" ? now : null, createdAt: now, updatedAt: now, connection: { id: randomUUID(), pageId: seed.id, status: seed.status, provider: "meta", encryptedToken: seed.metaPageId ? "preview-only" : null, connectedAt: seed.metaPageId ? now : null, lastError: null, subscribedAt: seed.metaPageId ? now : null, lastHealthCheckAt: seed.metaPageId ? now : null, lastHealthCheckStatus: seed.metaPageId ? "healthy" : null, createdAt: now, updatedAt: now }, settings: { id: randomUUID(), pageId: seed.id, currency: seed.currency, countryCode: "US", defaultLanguage: "en", tone: "helpful", requiredOrderFields: ["name", "phone", "address", "product", "variant", "quantity"], globalAiPaused: false, telegramEnabled: false, encryptedTelegramBotToken: null, telegramChatId: null, createdAt: now, updatedAt: now }, businessProfile: profile, products: [product], configurationVersions: [configuration], _count: { customers: 1, conversations: 1, products: 1 } } as unknown as PreviewPage;
}

type PreviewPageBudget = { usdBdtRate: number; monthlyBdt: number | null; dailyBdt: number | null; hardLimit: boolean; warningThreshold: number; pausedByBudget: boolean; reservedBdt: number };
type PreviewUsageAttempt = { id: string; pageId: string; callType: "CHAT_REPLY" | "BUSINESS_PARSE" | "MEMORY_SUMMARY" | "PRELIVE_TEST" | "RETRY"; model: "deepseek-v4-flash" | "deepseek-v4-pro"; inputTokens: number; cachedInputTokens: number; outputTokens: number; estimatedCostUsd: number; estimatedCostBdt: number; fxRate: number; status: "SUCCEEDED" | "FAILED"; createdAt: Date };
type PreviewState = { pages: PreviewPage[]; globalAiPaused: boolean; aiSettings: Map<string, PreviewAiSettings>; telegramSettings: Map<string, PreviewTelegramSettings>; pageBudgets: Map<string, PreviewPageBudget>; usage: Map<string, { calls: number; inputTokens: number; outputTokens: number; totalTokens: number; estimatedCost: number; estimatedCostBdt: number }>; usageAttempts: Map<string, PreviewUsageAttempt[]>; customerMemory: Map<string, PreviewCustomerMemory>; deletedCustomers: Set<string>; issues: PreviewIssue[]; control: PreviewControlCenter };
const previewGlobal = globalThis as typeof globalThis & { __growthifyxPreviewState?: PreviewState };
const previewState: PreviewState = previewGlobal.__growthifyxPreviewState ?? { pages: seeds.map(makePage), globalAiPaused: false, aiSettings: new Map(), telegramSettings: new Map(), pageBudgets: new Map(), usage: new Map(), usageAttempts: new Map(), customerMemory: new Map(), deletedCustomers: new Set(), issues: [], control: { globalAiPaused: false, general: { applicationName: "Growthifyx AI Sales", canonicalDomain: "https://ai.growthifyx.space", currency: "BDT", timezone: "Asia/Dhaka", country: "Bangladesh", language: "Auto" }, meta: { appId: "", appSecretConfigured: false, verifyTokenConfigured: false, graphApiVersion: "v23.0", loginConfigurationId: "", loginConfigurationConfigured: false, oauthRedirectUri: "https://ai.growthifyx.space/api/meta/oauth/callback", oauthRedirectConfigured: true, requiredPermissions: ["pages_show_list", "pages_read_engagement", "pages_manage_metadata", "pages_messaging", "business_management"], status: "NOT_CONFIGURED", lastError: null, lastTestAt: null }, ai: { provider: "DeepSeek", apiKeyConfigured: false, baseUrl: "https://api.deepseek.com", defaultModel: "deepseek-v4-flash", thinkingMode: "off", maxOutputTokens: 700, timeoutMs: 30000, retryCount: 1, status: "NOT_CONFIGURED", balanceUsd: null, balanceCny: null, lastBalanceAt: null }, telegram: { tokenConfigured: false, chatId: "", status: "NOT_CONFIGURED" }, fx: { usdBdtRate: 120, source: "MANUAL", updatedAt: now }, pricing: [{ model: "deepseek-v4-flash", inputCacheHitUsd: 0.1, inputCacheMissUsd: 0.3, outputUsd: 1.1, effectiveFrom: now, updatedAt: now }, { model: "deepseek-v4-pro", inputCacheHitUsd: 0.3, inputCacheMissUsd: 1.2, outputUsd: 4.5, effectiveFrom: now, updatedAt: now }], globalBudget: { monthlyBdt: null, dailyBdt: null, hardLimit: false, warningThreshold: 85, usedBdt: 0, reservedBdt: 0 } } };
previewGlobal.__growthifyxPreviewState = previewState;
let pages = previewState.pages;
const previewAiSettings = previewState.aiSettings;
const previewUsage = previewState.usage;
let issues: PreviewIssue[] = previewState.issues.length ? previewState.issues : [
  { id: "77777777-7777-4777-8777-777777777771", pageId: PAGE_IDS[1], type: "CONFIGURATION", status: "OPEN", severity: "medium", title: "Northstar draft has not been published", description: "The Page has a prepared catalog but its latest business configuration is still a draft.", resolutionAction: "Review the draft and publish it when ready.", createdAt: now, updatedAt: now, page: { id: PAGE_IDS[1], name: seeds[1].name, metaPageId: seeds[1].metaPageId } },
  { id: "77777777-7777-4777-8777-777777777772", pageId: PAGE_IDS[2], type: "META_CONNECTION", status: "OPEN", severity: "high", title: "Luna Wellness Studio is not connected", description: "Connect the Facebook Page before enabling live Messenger operations.", resolutionAction: "Reconnect the Facebook Page.", createdAt: now, updatedAt: now, page: { id: PAGE_IDS[2], name: seeds[2].name, metaPageId: null } },
  { id: "77777777-7777-4777-8777-777777777773", pageId: PAGE_IDS[0], type: "PREVIEW", status: "OPEN", severity: "low", title: "Development preview is active", description: "This data is local fixture data and is never used by production runtime.", resolutionAction: "Disable DEV_PREVIEW before production deployment.", createdAt: now, updatedAt: now, page: { id: PAGE_IDS[0], name: seeds[0].name, metaPageId: seeds[0].metaPageId } },
];
previewState.issues = issues;
export function persistPreviewState() { previewState.pages = pages; previewState.issues = issues; }
if (!previewState.pageBudgets) previewState.pageBudgets = new Map();
if (!previewState.telegramSettings) previewState.telegramSettings = new Map();
if (!previewState.usageAttempts) previewState.usageAttempts = new Map();
if (!previewState.customerMemory) previewState.customerMemory = new Map();
if (!previewState.deletedCustomers) previewState.deletedCustomers = new Set();
if (!previewState.control) throw new Error("Preview control center state is unavailable; restart preview mode.");
function pageKey(pageId: string) { const page = pageFor(pageId); return page.id; }
function pricingFor(model: "deepseek-v4-flash" | "deepseek-v4-pro") { return model === "deepseek-v4-pro" ? { inputCacheHitUsd: 0.3, inputCacheMissUsd: 1.2, outputUsd: 4.5 } : { inputCacheHitUsd: 0.1, inputCacheMissUsd: 0.3, outputUsd: 1.1 }; }
export function getPreviewControlCenter(): PreviewControlCenter { const control = structuredClone(previewState.control); return { ...control, globalAiPaused: previewState.globalAiPaused, general: control.general, meta: control.meta }; }
export function setPreviewGlobalAiPaused(paused: boolean) { previewState.globalAiPaused = paused; previewState.control.globalAiPaused = paused; return paused; }
export function updatePreviewMeta(input: { appId: string; appSecret?: string; verifyToken?: string; graphApiVersion?: string; loginConfigurationId?: string }) { const current = previewState.control.meta; const loginConfigurationId = input.loginConfigurationId?.trim() || current.loginConfigurationId || ""; previewState.control.meta = { ...current, appId: input.appId.trim(), appSecretConfigured: Boolean(input.appSecret?.trim()) || current.appSecretConfigured, verifyTokenConfigured: Boolean(input.verifyToken?.trim()) || current.verifyTokenConfigured, graphApiVersion: input.graphApiVersion?.trim() || current.graphApiVersion, loginConfigurationId, loginConfigurationConfigured: Boolean(loginConfigurationId), status: input.appId.trim() && (Boolean(input.appSecret?.trim()) || current.appSecretConfigured) && (Boolean(input.verifyToken?.trim()) || current.verifyTokenConfigured) && Boolean(loginConfigurationId) ? "READY" : "DEGRADED", lastError: null }; return getPreviewControlCenter().meta; }
export function testPreviewMeta() { previewState.control.meta = { ...previewState.control.meta, status: previewState.control.meta.appId && previewState.control.meta.appSecretConfigured ? "READY" : "ERROR", lastError: previewState.control.meta.appId && previewState.control.meta.appSecretConfigured ? null : "Configure the App ID and App Secret first.", lastTestAt: new Date() }; return getPreviewControlCenter().meta; }
function pageBudgetDefaults(pageId?: string): PreviewPageBudget { const index = pages.findIndex((page) => page.id === pageId); return { usdBdtRate: 120, monthlyBdt: index === 0 ? 500 : index === 1 ? 300 : null, dailyBdt: null, hardLimit: index < 2, warningThreshold: 85, pausedByBudget: false, reservedBdt: 0 }; }
export function getPreviewPageBudget(pageId: string) { const key = pageKey(pageId); return { ...pageBudgetDefaults(key), ...(previewState.pageBudgets.get(key) ?? {}) }; }
export function getPreviewBudgetSummary(pageId: string) { const page = pageFor(pageId); const budget = getPreviewPageBudget(page.id); const usage = getPreviewUsage(page.id).month; const usedBdt = usage.estimatedCostBdt; return { ...budget, usedBdt, remainingBdt: budget.monthlyBdt === null ? null : Math.max(0, budget.monthlyBdt - usedBdt), state: budget.pausedByBudget ? "PAUSED_BY_BUDGET" : budget.monthlyBdt !== null && usedBdt >= budget.monthlyBdt ? "LIMIT_REACHED" : budget.monthlyBdt !== null && usedBdt >= budget.monthlyBdt * budget.warningThreshold / 100 ? "WARNING" : "HEALTHY", calls: usage.calls, inputTokens: usage.inputTokens, cachedInputTokens: 0, outputTokens: usage.outputTokens, estimatedUsd: usage.estimatedCost, costBdt: usedBdt }; }
export function updatePreviewPageBudget(pageId: string, input: Partial<PreviewPageBudget>) { const key = pageKey(pageId); const next = { ...getPreviewPageBudget(key), ...input }; previewState.pageBudgets.set(key, next); if (next.monthlyBdt !== null && getPreviewBudgetSummary(key).usedBdt >= next.monthlyBdt && next.hardLimit) { next.pausedByBudget = true; setPreviewAi(false, key); pages = pages.map((item) => item.id === key ? { ...item, aiStatus: "PAUSED_BY_BUDGET" } as PreviewPage : item); createPreviewIssue({ pageId: key, type: "PAGE_BUDGET_LIMIT", title: `${pageFor(key).name} AI is paused by budget`, description: "The Page monthly AI budget has been reached. Incoming messages continue to be stored.", severity: "high", resolutionAction: "Increase the Page budget or resume AI." }); } persistPreviewState(); return getPreviewBudgetSummary(key); }
export function forcePreviewPageBudgetLimit(pageId: string) { const key = pageKey(pageId); const budget = getPreviewPageBudget(key); const usedBdt = getPreviewUsage(key).month.estimatedCostBdt; const next = { ...budget, monthlyBdt: Math.max(0.01, Math.min(budget.monthlyBdt ?? 999999, usedBdt || 0.01)), hardLimit: true, pausedByBudget: true }; previewState.pageBudgets.set(key, next); setPreviewAi(false, key); pages = pages.map((item) => item.id === key ? { ...item, aiStatus: "PAUSED_BY_BUDGET" } as PreviewPage : item); createPreviewIssue({ pageId: key, type: "PAGE_BUDGET_LIMIT", title: `${pageFor(key).name} AI is paused by budget`, description: "Preview simulation reached the Page hard limit.", severity: "high", resolutionAction: "Increase the Page budget or resume AI." }); persistPreviewState(); return getPreviewBudgetSummary(key); }
export function resumePreviewPageAi(pageId: string) { const key = pageKey(pageId); const budget = getPreviewPageBudget(key); previewState.pageBudgets.set(key, { ...budget, pausedByBudget: false }); setPreviewAi(true, key); persistPreviewState(); return getPreviewBudgetSummary(key); }
function pageFor(pageId?: string) { const page = pages.find((item) => item.id === pageId || item.slug === pageId); if (!page) throw new Error("Page not found"); return page; }
export function resolvePreviewPageId(idOrSlug: string) { return getPreviewPage(idOrSlug)?.id ?? null; }
const previewFacebookCatalog = [{ id: "preview-meta-page-001", name: "Karseell Bangladesh" }, { id: "preview-meta-page-002", name: "Growthifyx Demo Store" }, { id: "preview-meta-page-003", name: "Demo Fashion" }] as const;
export function getPreviewFacebookPages() { const connected = new Set(pages.map((page) => page.metaPageId).filter((id): id is string => Boolean(id))); return previewFacebookCatalog.filter((candidate) => !connected.has(candidate.id)); }
export function getPreviewFacebookPage(metaPageId: string) { return previewFacebookCatalog.find((candidate) => candidate.id === metaPageId) ?? null; }
function applyGlobalPause(page: PreviewPage) { return previewState.globalAiPaused && page.aiEnabled ? { ...page, aiEnabled: false, aiStatus: "PAUSED" } as PreviewPage : page; }
export function getPreviewPages() { return pages.map(applyGlobalPause); }
export function getPreviewTelegramSettings(pageId: string): PreviewTelegramSettings { const page = pageFor(pageId); const stored = previewState.telegramSettings.get(page.id); if (stored) return { ...stored }; const index = pages.findIndex((item) => item.id === page.id); return { tokenConfigured: index === 0 || index === 1, accountLabel: index === 0 ? "Telegram A" : index === 1 ? "Telegram B" : "Not configured", chatId: index === 0 ? "-100000000001" : index === 1 ? "-100000000002" : "", newOrderEnabled: true, updatedOrderEnabled: true, cancelledOrderEnabled: true, status: index < 2 ? "CONNECTED" : "NOT_CONFIGURED", lastTestAt: null }; }
export function updatePreviewTelegramSettings(pageId: string, input: Partial<PreviewTelegramSettings> & { botToken?: string }) { const key = pageKey(pageId); const current = getPreviewTelegramSettings(key); const next = { ...current, ...input, tokenConfigured: Boolean(input.botToken?.trim()) || current.tokenConfigured }; delete (next as Partial<PreviewTelegramSettings> & { botToken?: string }).botToken; previewState.telegramSettings.set(key, next); return next; }
export function testPreviewTelegram(pageId: string, candidateToken?: string, candidateChatId?: string) { const current = getPreviewTelegramSettings(pageId); const chatId = candidateChatId?.trim() || current.chatId; const connected = (Boolean(candidateToken?.trim()) || current.tokenConfigured) && Boolean(chatId); const next = { ...current, chatId, status: connected ? "CONNECTED" as const : "ERROR" as const, lastTestAt: new Date() }; previewState.telegramSettings.set(pageKey(pageId), next); if (!connected) createPreviewIssue({ pageId: pageKey(pageId), type: "TELEGRAM", title: `${pageFor(pageId).name} Telegram needs attention`, description: "Configure a bot token and Chat / Group ID before testing Telegram.", severity: "medium", resolutionAction: "Configure Telegram for this Page." }); return next; }
export function getPreviewPage(idOrSlug: string) { const page = pages.find((item) => item.id === idOrSlug || item.slug === idOrSlug) ?? null; return page ? applyGlobalPause(page) : null; }
export function getPreviewDashboard() { return { pages: pages.map((rawPage) => { const page = applyGlobalPause(rawPage); const usage = getPreviewUsage(page.id).month; const budget = getPreviewBudgetSummary(page.id); const telegram = getPreviewTelegramSettings(page.id); return { id: page.id, slug: page.slug, name: page.name, connectionStatus: page.connectionStatus, aiEnabled: page.aiEnabled, telegramStatus: telegram.status, budgetState: budget.state, usage: { calls: usage.calls, totalTokens: usage.totalTokens, estimatedCost: usage.estimatedCost, estimatedCostBdt: usage.estimatedCostBdt } }; }) }; }
export function connectPreviewPage(id: string, metaPageId: string, name?: string) { const current = getPreviewPage(id); if (!current) return null; const candidate = getPreviewFacebookPage(metaPageId); if (!candidate) throw new Error("That Facebook Page is not available in preview."); const duplicate = pages.find((item) => item.id !== current.id && item.metaPageId === metaPageId); if (duplicate) throw new Error("That Facebook Page is already connected."); pages = pages.map((item) => item.id === current.id ? { ...item, name: candidate.name || name || item.name, metaPageId, connectionStatus: "CONNECTED", lifecycleStatus: "DRAFT", connection: { ...item.connection!, status: "CONNECTED", encryptedToken: "preview-only", connectedAt: new Date(), lastHealthCheckAt: new Date(), lastHealthCheckStatus: "healthy" } } as PreviewPage : item); persistPreviewState(); return getPreviewPage(current.id); }
export function createPreviewPage(name: string) { const id = randomUUID(); const base = { ...makePage({ ...seeds[2], id, name, slug: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${id.slice(0, 8)}`, metaPageId: null, product: { ...seeds[2].product, stockStatus: "IN_STOCK" } }), aiEnabled: false, aiStatus: "SETUP_REQUIRED" } as PreviewPage; pages = [...pages, base]; persistPreviewState(); return base; }
export function savePreviewBusiness(input: { pageId?: string; rawBusinessInfo: string; businessName?: string; description?: string; benefits?: string; deliveryPolicy?: string; codPolicy?: string; faq?: string; salesInstructions?: string; notes?: string }) { const current = pageFor(input.pageId); const version = Math.max(...current.configurationVersions.map((item) => item.version), 0) + 1; const previous = current.configurationVersions[0]; const draft = { ...previous, id: randomUUID(), version, status: "DRAFT", label: `Preview draft ${version}`, rawBusinessInfo: input.rawBusinessInfo, businessData: { ...(previous.businessData as object), business_profile: { business_name: input.businessName ?? null, description: input.description ?? null, benefits: (input.benefits ?? "").split("\n").filter(Boolean) }, policies: { delivery: input.deliveryPolicy ?? null, cod: input.codPolicy ?? null, faq: (input.faq ?? "").split("\n").filter(Boolean) }, sales_instructions: input.salesInstructions ?? null, order_requirements: (input.notes ?? "").split("\n").filter(Boolean), conflicts: [] }, parseStatus: "READY", publishedAt: null, createdAt: new Date() }; pages = pages.map((item) => item.id === current.id ? { ...item, configurationVersions: [draft, ...item.configurationVersions] } as PreviewPage : item); persistPreviewState(); return draft; }
export function createPreviewProduct(input: { pageId?: string; name: string; description?: string; sku: string; price: number; oldPrice?: number; size?: string; color?: string }) { const current = pageFor(input.pageId); const productId = randomUUID(); const timestamp = new Date(); const product = { id: productId, pageId: current.id, name: input.name, slug: input.sku.toLowerCase(), description: input.description ?? null, benefits: [], tags: [], active: true, createdAt: timestamp, updatedAt: timestamp, variants: [{ id: randomUUID(), productId, sku: input.sku, size: input.size ?? null, color: input.color ?? null, currentPrice: input.price, oldPrice: input.oldPrice ?? null, stockStatus: "IN_STOCK", active: true, createdAt: timestamp, updatedAt: timestamp }] } as unknown as PreviewPage["products"][number]; const version = Math.max(...current.configurationVersions.map((item) => item.version), 0) + 1; const products = current.products.concat(product).map((item) => ({ name: item.name, description: item.description, tags: Array.isArray(item.tags) ? item.tags : [], variants: item.variants.map((variant) => ({ sku: variant.sku, size: variant.size, color: variant.color, current_price: Number(variant.currentPrice), old_price: variant.oldPrice === null ? null : Number(variant.oldPrice) })) })); const draft = { ...current.configurationVersions[0], id: randomUUID(), version, status: "DRAFT", label: `Catalog preview draft ${version}`, businessData: { ...(current.configurationVersions[0].businessData as object), products }, createdAt: timestamp, publishedAt: null }; pages = pages.map((item) => item.id === current.id ? { ...item, products: [...item.products, product], _count: { ...item._count, products: item.products.length + 1 }, configurationVersions: [draft, ...item.configurationVersions] } as PreviewPage : item); persistPreviewState(); return draft; }
export function updatePreviewProduct(input: { pageId: string; productId: string; name: string; description?: string; sku: string; price: number; oldPrice?: number; size?: string; color?: string; active?: boolean }) { const current = getPreviewPage(input.pageId); if (!current) throw new Error("Page not found"); const timestamp = new Date(); let updated: PreviewPage["products"][number] | null = null; const products = current.products.map((product) => { if (product.id !== input.productId) return product; updated = { ...product, name: input.name, description: input.description ?? null, active: input.active ?? product.active, updatedAt: timestamp, variants: product.variants.map((variant, index) => index === 0 ? { ...variant, sku: input.sku, currentPrice: input.price, oldPrice: input.oldPrice ?? null, size: input.size ?? null, color: input.color ?? null, updatedAt: timestamp } : variant) } as PreviewPage["products"][number]; return updated; }); if (!updated) throw new Error("Product not found"); pages = pages.map((item) => item.id === input.pageId ? { ...item, products } as PreviewPage : item); persistPreviewState(); return updated; }
export function setPreviewProductActive(pageId: string, productId: string, active: boolean) { const current = getPreviewPage(pageId); if (!current) throw new Error("Page not found"); pages = pages.map((item) => item.id === pageId ? { ...item, products: item.products.map((product) => product.id === productId ? { ...product, active, variants: product.variants.map((variant) => ({ ...variant, active })) } : product) } as PreviewPage : item); persistPreviewState(); return getPreviewPage(pageId); }
export function deletePreviewProduct(pageId: string, productId: string) { const current = getPreviewPage(pageId); if (!current) throw new Error("Page not found"); pages = pages.map((item) => item.id === pageId ? { ...item, products: item.products.filter((product) => product.id !== productId), _count: { ...item._count, products: Math.max(0, item.products.length - 1) } } as PreviewPage : item); persistPreviewState(); }
export function publishPreview(pageId: string) { const current = getPreviewPage(pageId); if (!current) throw new Error("Page not found"); const draft = current.configurationVersions.find((version) => version.status === "DRAFT"); if (!draft) throw new Error("No draft configuration to publish"); pages = pages.map((item) => item.id === pageId ? { ...item, lifecycleStatus: "LIVE", configurationVersions: item.configurationVersions.map((version) => ({ ...version, status: version.id === draft.id ? "LIVE" : version.status === "LIVE" ? "ARCHIVED" : version.status, publishedAt: version.id === draft.id ? new Date() : version.publishedAt })) } as PreviewPage : item); persistPreviewState(); return draft; }
export function rollbackPreview(pageId: string, version: number) { const current = getPreviewPage(pageId); const target = current?.configurationVersions.find((item) => item.version === version); if (!current || !target) throw new Error("Configuration version not found"); pages = pages.map((item) => item.id === pageId ? { ...item, configurationVersions: item.configurationVersions.map((versionItem) => ({ ...versionItem, status: versionItem.id === target.id ? "LIVE" : versionItem.status === "LIVE" ? "ARCHIVED" : versionItem.status })) } as PreviewPage : item); persistPreviewState(); return target; }
export function setPreviewAi(enabled: boolean, pageId?: string) { const current = pageId ? getPreviewPage(pageId) : pageFor(); if (!current) return null; if (enabled && previewState.globalAiPaused) return applyGlobalPause(current); const nextStatus = enabled ? (getPreviewPageBudget(current.id).pausedByBudget ? "PAUSED_BY_BUDGET" : "RUNNING") : "PAUSED"; pages = pages.map((item) => item.id === current.id ? { ...item, aiEnabled: enabled && !getPreviewPageBudget(current.id).pausedByBudget, aiStatus: nextStatus } as PreviewPage : item); persistPreviewState(); return pageFor(current.id); }
export function getPreviewAiSettings(pageId: string) { const page = pageFor(pageId); const index = pages.findIndex((item) => item.id === page.id); const configured = index === 0 || index === 1; const base = previewAiSettings.get(page.id) ?? { ...defaultAiSettings, apiKeyConfigured: configured, accountLabel: index === 0 ? "AI account A" : index === 1 ? "AI account B" : "Not configured", providerStatus: configured ? "CONNECTED" : "NOT_CONFIGURED", providerBalanceUsd: index === 0 ? 18.42 : index === 1 ? 9.75 : null, providerBalanceCny: index === 0 ? 132.6 : index === 1 ? 70.2 : null, lastBalanceAt: configured ? now : null }; return { ...base }; }
export function testPreviewAiCredential(pageId: string, apiKey?: string) { const current = getPreviewAiSettings(pageId); const valid = Boolean(apiKey?.trim()) || current.apiKeyConfigured; return { ok: valid, settings: { ...current, providerStatus: valid ? "CONNECTED" as const : "ERROR" as const }, error: valid ? null : "Enter a Page API key before testing the credential." }; }
export function updatePreviewAiSettings(pageId: string, input: Partial<PreviewAiSettings> & { apiKey?: string }) { const key = pageKey(pageId); const current = getPreviewAiSettings(key); const value = { ...current, ...input, apiKeyConfigured: Boolean(input.apiKey?.trim()) || current.apiKeyConfigured, accountLabel: current.accountLabel, avoidRepeatedQuestions: true as const, staleReplyProtection: true as const, sequentialProcessing: true as const }; delete (value as Partial<PreviewAiSettings> & { apiKey?: string }).apiKey; previewAiSettings.set(key, value); return value; }
export function refreshPreviewPageBalance(pageId: string) { const current = getPreviewAiSettings(pageId); return updatePreviewAiSettings(pageId, { providerBalanceUsd: (current.providerBalanceUsd ?? 0) + 0.01, providerBalanceCny: (current.providerBalanceCny ?? 0) + 0.1, lastBalanceAt: new Date(), providerStatus: current.apiKeyConfigured ? "CONNECTED" : "NOT_CONFIGURED" }); }
export function runPreviewAiTest(pageId: string, message: string) { const page = getPreviewPage(pageId); if (!page) throw new Error("Page not found"); const settings = getPreviewAiSettings(page.id); const configured = settings.apiKeyConfigured; const product = page.products.find((item) => item.active && item.variants.some((variant) => variant.active)); const blocked = previewState.globalAiPaused || page.aiStatus === "PAUSED_BY_BUDGET"; const reply = blocked ? `AI is paused for ${page.name}. The test did not create a provider attempt.` : configured ? `Provider test for ${page.name}: I can help with ${product?.name ?? "your products"}.` : `Mock reply for ${page.name}: I can help with ${product?.name ?? "our products"}. What would you like to know?`; const model = settings.modelOverride === "deepseek-v4-pro" ? "deepseek-v4-pro" : "deepseek-v4-flash"; const pricing = pricingFor(model); const estimatedUsd = 84 / 1_000_000 * pricing.inputCacheMissUsd + 34 / 1_000_000 * pricing.outputUsd; if (!blocked) recordPreviewUsage(page.id, 84, 34, estimatedUsd, undefined, { callType: "PRELIVE_TEST", model }); const summary = getPreviewBudgetSummary(page.id); const budget = getPreviewPageBudget(page.id); if (budget.hardLimit && summary.monthlyBdt !== null && summary.usedBdt >= summary.monthlyBdt && !budget.pausedByBudget) updatePreviewPageBudget(page.id, { pausedByBudget: true }); return { reply, label: blocked ? "PAUSED" : configured ? "PREVIEW" : "MOCK", model, intent: message.toLowerCase().includes("price") ? "PRICE_INQUIRY" : "GENERAL_INQUIRY", factsExtracted: [], productsSelected: blocked ? [] : product ? [product.name] : [], questionKey: "customer_need", validationResult: blocked ? "SKIPPED" : "PASS", tokenUsage: { input: blocked ? 0 : 84, output: blocked ? 0 : 34, total: blocked ? 0 : 118 }, estimatedUsd: blocked ? 0 : estimatedUsd, estimatedBdt: blocked ? 0 : estimatedUsd * getPreviewPageBudget(page.id).usdBdtRate, latencyMs: 42 }; }
export function updatePreviewSettings(input: { pageId?: string; currency: string; countryCode: string; defaultLanguage: string; tone: string; requiredOrderFields: string[] }) { const current = pageFor(input.pageId); pages = pages.map((item) => item.id === current.id ? { ...item, settings: { ...item.settings!, ...input, updatedAt: new Date() } } as PreviewPage : item); return pageFor(current.id).settings; }
export const safeSettingsCopyFields = ["AI behavior", "Memory settings", "Message handling", "Order required fields", "Budget warning percentage"] as const;
export function copyPreviewSettings(fromPageId: string, toPageId: string) { const source = pageFor(fromPageId); const target = pageFor(toPageId); const sourceAi = getPreviewAiSettings(source.id); const targetAi = getPreviewAiSettings(target.id); const aiFields = ["language", "tone", "replyLength", "understandBeforeRecommend", "maxProductsPerRecommendation", "suggestCombo", "askOneQuestionAtATime", "mirrorCustomerLanguage", "customerMemory", "recentMessageContext", "rollingSummary", "smartBuffer", "bufferWindowSeconds", "manualCollisionProtection", "manualActivityCooldownSeconds"] as const; const copiedAi = Object.fromEntries(aiFields.map((key) => [key, sourceAi[key]])); previewAiSettings.set(target.id, { ...targetAi, ...copiedAi }); pages = pages.map((item) => item.id === target.id ? { ...item, settings: { ...item.settings!, requiredOrderFields: [...(source.settings?.requiredOrderFields as string[] ?? [])], updatedAt: new Date() } } as PreviewPage : item); const sourceBudget = getPreviewPageBudget(source.id); previewState.pageBudgets.set(target.id, { ...getPreviewPageBudget(target.id), warningThreshold: sourceBudget.warningThreshold }); persistPreviewState(); return { pageId: target.id, fields: [...safeSettingsCopyFields] };
}
export function setPreviewLive(pageId?: string) { const current = pageId ? getPreviewPage(pageId) : null; if (!current) return null; pages = pages.map((item) => item.id === current.id ? { ...item, lifecycleStatus: "LIVE", aiEnabled: current.aiEnabled, aiStatus: current.aiEnabled ? "RUNNING" : "SETUP_REQUIRED", readinessCheckedAt: new Date() } as PreviewPage : item); persistPreviewState(); return pageFor(current.id); }
export function getPreviewIssues() { return issues.filter((issue) => issue.status !== "RESOLVED"); }
export function createPreviewIssue(input: { pageId?: string; type: string; title: string; description: string; severity?: string; resolutionAction?: string }) {
  const page = input.pageId ? getPreviewPage(input.pageId) : null;
  const issue: PreviewIssue = { id: randomUUID(), pageId: input.pageId ?? null, type: input.type, status: "OPEN", severity: input.severity ?? "medium", title: input.title, description: input.description, resolutionAction: input.resolutionAction ?? null, createdAt: new Date(), updatedAt: new Date(), page: page ? { id: page.id, name: page.name, metaPageId: page.metaPageId } : null };
  issues = [issue, ...issues];
  return issue;
}
export function resolvePreviewIssue(id: string) { issues = issues.map((issue) => issue.id === id ? { ...issue, status: "RESOLVED", updatedAt: new Date() } : issue); }
export function getPreviewOrders(pageId?: string): PreviewOrder[] { return pages.filter((item) => !pageId || item.id === pageId).flatMap((page) => { const seed = seeds.find((item) => item.id === page.id); if (!seed) return []; const deleted = previewState.deletedCustomers.has(seed.customer.id); const quantity = page.id === PAGE_IDS[1] ? 1 : 2; return [{ id: `${page.id.slice(0, 8)}-order-0001`, pageId: page.id, customerId: deleted ? `deleted:${page.id}` : seed.customer.id, orderSessionId: `${page.id.slice(0, 8)}-session-01`, status: page.id === PAGE_IDS[2] ? "CANCELLED" : "CONFIRMED", total: seed.product.price * quantity, payload: deleted ? { customer_data_removed: true } : {}, productId: seed.product.id, productName: seed.product.name, variantId: `${seed.product.id.slice(0, 8)}-variant`, variantDetails: { sku: seed.product.sku, size: seed.product.size }, unitPrice: seed.product.price, quantity, currency: seed.currency, customerName: deleted ? "Deleted customer" : seed.customer.name, normalizedPhone: deleted ? "" : seed.customer.phone, phoneOriginal: deleted ? "" : seed.customer.phone, fullAddress: deleted ? "" : seed.customer.address, configurationVersion: 1, confirmedAt: now, createdAt: now, updatedAt: now, revisions: [] }]; }); }
export function getPreviewConversations(pageId?: string) { return pages.filter((item) => !pageId || item.id === pageId).flatMap((page) => { const seed = seeds.find((item) => item.id === page.id); return seed ? [{ id: seed.conversation.id, pageId: page.id, customerName: seed.customer.name, lastMessage: seed.conversation.lastMessage, status: seed.conversation.status, updatedAt: now }] : []; }); }
export function getPreviewCustomers(pageId?: string) { return pages.filter((item) => !pageId || item.id === pageId).flatMap((page) => { const seed = seeds.find((item) => item.id === page.id); return seed && !previewState.deletedCustomers.has(seed.customer.id) ? [{ id: seed.customer.id, pageId: page.id, name: seed.customer.name, phone: seed.customer.phone, orders: page.id === PAGE_IDS[2] ? 0 : 1, lastSeenAt: now }] : []; }); }
export function recordPreviewUsage(pageId: string, inputTokens: number, outputTokens: number, estimatedCost: number, estimatedCostBdt = estimatedCost * getPreviewPageBudget(pageId).usdBdtRate, metadata?: { callType?: PreviewUsageAttempt["callType"]; model?: PreviewUsageAttempt["model"]; cachedInputTokens?: number; status?: PreviewUsageAttempt["status"] }) { const key = pageKey(pageId); const current = previewUsage.get(key) ?? { calls: 0, inputTokens: 0, outputTokens: 0, totalTokens: 0, estimatedCost: 0, estimatedCostBdt: 0 }; previewUsage.set(key, { calls: current.calls + 1, inputTokens: current.inputTokens + inputTokens, outputTokens: current.outputTokens + outputTokens, totalTokens: current.totalTokens + inputTokens + outputTokens, estimatedCost: current.estimatedCost + estimatedCost, estimatedCostBdt: current.estimatedCostBdt + estimatedCostBdt }); const attempts = previewState.usageAttempts.get(key) ?? []; attempts.push({ id: randomUUID(), pageId: key, callType: metadata?.callType ?? "PRELIVE_TEST", model: metadata?.model ?? "deepseek-v4-flash", inputTokens, cachedInputTokens: metadata?.cachedInputTokens ?? 0, outputTokens, estimatedCostUsd: estimatedCost, estimatedCostBdt, fxRate: getPreviewPageBudget(key).usdBdtRate, status: metadata?.status ?? "SUCCEEDED", createdAt: new Date() }); previewState.usageAttempts.set(key, attempts); persistPreviewState(); }
export function getPreviewUsage(pageId?: string) { const page = pageId ? getPreviewPage(pageId) : null; const seed = seeds.find((item) => item.id === page?.id); const base = seed?.usage ?? { today: [0, 0, 0, 0, 0] as [number, number, number, number, number], month: [0, 0, 0, 0, 0] as [number, number, number, number, number], daily: [] as Array<[string, number, number, number, number]> }; const [todayCalls, todayInput, todayOutput, todayTotal, todayCost] = base.today; const [monthCalls, monthInput, monthOutput, monthTotal, monthCost] = base.month; const key = page?.id ?? pageId ?? PAGE_IDS[0]; const extra = previewUsage.get(key); const attempts = previewState.usageAttempts.get(key) ?? []; const cachedInputTokens = attempts.reduce((sum, attempt) => sum + attempt.cachedInputTokens, 0); const today = { calls: todayCalls + (extra?.calls ?? 0), inputTokens: todayInput + (extra?.inputTokens ?? 0), cachedInputTokens, outputTokens: todayOutput + (extra?.outputTokens ?? 0), totalTokens: todayTotal + (extra?.totalTokens ?? 0), estimatedCost: todayCost + (extra?.estimatedCost ?? 0), estimatedCostUsd: todayCost + (extra?.estimatedCost ?? 0), estimatedCostBdt: todayCost * 120 + (extra?.estimatedCostBdt ?? 0) }; const month = { calls: monthCalls + (extra?.calls ?? 0), inputTokens: monthInput + (extra?.inputTokens ?? 0), cachedInputTokens, outputTokens: monthOutput + (extra?.outputTokens ?? 0), totalTokens: monthTotal + (extra?.totalTokens ?? 0), estimatedCost: monthCost + (extra?.estimatedCost ?? 0), estimatedCostUsd: monthCost + (extra?.estimatedCost ?? 0), estimatedCostBdt: monthCost * 120 + (extra?.estimatedCostBdt ?? 0) }; const daily = [...base.daily.map(([date, calls, inputTokens, outputTokens, estimatedCost]) => ({ date, calls, inputTokens, cachedInputTokens: 0, outputTokens, totalTokens: inputTokens + outputTokens, estimatedCost, estimatedCostUsd: estimatedCost, estimatedCostBdt: estimatedCost * 120 })), ...attempts.map((attempt) => ({ date: attempt.createdAt.toISOString().slice(0, 10), calls: 1, inputTokens: attempt.inputTokens, cachedInputTokens: attempt.cachedInputTokens, outputTokens: attempt.outputTokens, totalTokens: attempt.inputTokens + attempt.outputTokens, estimatedCost: attempt.estimatedCostUsd, estimatedCostUsd: attempt.estimatedCostUsd, estimatedCostBdt: attempt.estimatedCostBdt }))]; return { today, month, daily }; }

function previewMemoryKey(pageId: string, customerId: string) { const page = getPreviewPage(pageId); const seed = page && seeds.find((item) => item.id === page.id); if (!page || !seed || seed.customer.id !== customerId || previewState.deletedCustomers.has(customerId)) throw new Error("Customer does not belong to page"); return `${page.id}:${customerId}`; }
function newPreviewMemory(pageId: string, customerId: string): PreviewCustomerMemory { return { pageId, customerId, memory: { knownFacts: { name: seeds.find((item) => item.id === pageId)?.customer.name ?? "" }, unconfirmedFacts: {}, needs: ["delivery timing"], preferences: { preferred_product_type: "everyday care" }, semanticQuestionsAsked: ["name"], recommendedProductIds: [], rejectedProductIds: [], activeOrderReference: `${pageId.slice(0, 8)}-session-01`, summary: "Preview customer memory is ready for inspection." }, facts: [{ id: `${customerId}-name-v1`, pageId, customerId, factKey: "name", normalizedValue: seeds.find((item) => item.id === pageId)?.customer.name ?? "", displayValue: seeds.find((item) => item.id === pageId)?.customer.name ?? "", sourceType: "CUSTOMER_CONFIRMED", status: "ACTIVE", lastConfirmedAt: now, updatedAt: now }], summaryStale: false, summaryVersion: 1 }; }
function previewMemory(pageId: string, customerId: string) { const key = previewMemoryKey(pageId, customerId); const current = previewState.customerMemory.get(key) ?? newPreviewMemory(pageId, customerId); previewState.customerMemory.set(key, current); return current; }
export function getPreviewCustomerMemory(pageId: string, customerId: string) { const memory = previewMemory(pageId, customerId); return structuredClone(memory); }
function updatePreviewMemory(pageId: string, customerId: string, fn: (memory: PreviewCustomerMemory) => void) { const memory = previewMemory(pageId, customerId); fn(memory); memory.summaryStale = true; memory.facts = memory.facts.map((fact) => ({ ...fact })); previewState.customerMemory.set(`${pageId}:${customerId}`, memory); persistPreviewState(); return structuredClone(memory); }
export function editPreviewCustomerFact(input: { pageId: string; customerId: string; factKey: string; value: string }) { if (!input.value.trim()) throw new Error("A fact value is required"); return updatePreviewMemory(input.pageId, input.customerId, (memory) => { const current = memory.facts.find((fact) => fact.factKey === input.factKey && fact.status === "ACTIVE"); if (current) { current.status = "SUPERSEDED"; current.supersededByFactId = `${input.customerId}-${input.factKey}-${Date.now()}`; } const id = `${input.customerId}-${input.factKey}-${Date.now()}`; memory.facts.unshift({ id, pageId: input.pageId, customerId: input.customerId, factKey: input.factKey, normalizedValue: input.value.trim(), displayValue: input.value.trim(), sourceType: "ADMIN_CORRECTION", status: "ACTIVE", lastConfirmedAt: new Date(), updatedAt: new Date() }); memory.memory.knownFacts[input.factKey] = input.value.trim(); delete memory.memory.unconfirmedFacts[input.factKey]; }); }
export function markPreviewCustomerFactUnknown(input: { pageId: string; customerId: string; factKey: string }) { return updatePreviewMemory(input.pageId, input.customerId, (memory) => { for (const fact of memory.facts.filter((item) => item.factKey === input.factKey && item.status === "ACTIVE")) fact.status = "REJECTED"; delete memory.memory.knownFacts[input.factKey]; delete memory.memory.unconfirmedFacts[input.factKey]; }); }
export function removePreviewCustomerFact(input: { pageId: string; customerId: string; factKey: string }) { return markPreviewCustomerFactUnknown(input); }
export function clearPreviewNonOrderMemory(input: { pageId: string; customerId: string }) { return updatePreviewMemory(input.pageId, input.customerId, (memory) => { for (const fact of memory.facts.filter((item) => item.factKey !== "active_order_session_id" && ["ACTIVE", "UNCONFIRMED"].includes(item.status))) fact.status = "REJECTED"; const activeOrderReference = memory.memory.activeOrderReference; memory.memory = { knownFacts: {}, unconfirmedFacts: {}, needs: [], preferences: {}, semanticQuestionsAsked: [], recommendedProductIds: [], rejectedProductIds: [], activeOrderReference, summary: "" }; }); }
export function rebuildPreviewCustomerSummary(input: { pageId: string; customerId: string }) { const memory = previewMemory(input.pageId, input.customerId); const facts = Object.entries(memory.memory.knownFacts).map(([key, value]) => `${key}=${String(value)}`).join("; "); memory.memory.summary = `Known facts: ${facts || "none"}\nRecent turns: Preview conversation available.`.slice(0, 4000); memory.summaryStale = false; memory.summaryVersion += 1; memory.facts = memory.facts.map((fact) => ({ ...fact })); previewState.customerMemory.set(`${input.pageId}:${input.customerId}`, memory); persistPreviewState(); return structuredClone(memory); }
export function deletePreviewCustomerData(input: { pageId: string; customerId: string; requestKey: string }) { const page = getPreviewPage(input.pageId); const seed = page && seeds.find((item) => item.id === page.id); if (!page || !seed || seed.customer.id !== input.customerId) throw new Error("Customer does not belong to page"); const alreadyCompleted = previewState.deletedCustomers.has(input.customerId); previewState.deletedCustomers.add(input.customerId); previewState.customerMemory.delete(`${page.id}:${input.customerId}`); persistPreviewState(); return { requestKey: input.requestKey, pageId: page.id, customerId: input.customerId, alreadyCompleted, ordersPreserved: getPreviewOrders(page.id).length }; }
