"use client";

import { useState } from "react";

type Settings = {
  language: string; tone: string; replyLength: string; understandBeforeRecommend: boolean; avoidRepeatedQuestions: true;
  maxProductsPerRecommendation: 1 | 2; suggestCombo: boolean; askOneQuestionAtATime: boolean; mirrorCustomerLanguage: boolean;
  customerMemory: boolean; recentMessageContext: number; rollingSummary: boolean; smartBuffer: boolean; bufferWindowSeconds: number;
  manualCollisionProtection: boolean; manualActivityCooldownSeconds: number; staleReplyProtection: true; sequentialProcessing: true;
  customSalesInstructions: string;
  modelOverride?: "master" | "deepseek-v4-flash" | "deepseek-v4-pro";
  thinking?: "master" | "off" | "on";
  maxOutputTokens?: number;
};
type Result = { reply: string; label: string; intent: string; factsExtracted: string[]; productsSelected: string[]; questionKey: string; validationResult: string; tokenUsage: { total: number }; latencyMs: number };

export function AiSettingsPanel({ pageId, initial, aiEnabled }: { pageId: string; initial: Settings; aiEnabled: boolean }) {
  const [value, setValue] = useState(initial); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const [testMessage, setTestMessage] = useState("What do you recommend for dry hair?"); const [result, setResult] = useState<Result | null>(null); const [testing, setTesting] = useState(false);
  const set = <K extends keyof Settings>(key: K, next: Settings[K]) => setValue((current) => ({ ...current, [key]: next }));
  async function save() { setLoading(true); setMessage(""); try { const response = await fetch(`/api/pages/${pageId}/ai/settings`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to save AI settings."); setMessage("AI settings saved for this Page."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save AI settings."); } finally { setLoading(false); } }
  async function runTest() { setTesting(true); setResult(null); try { const response = await fetch(`/api/pages/${pageId}/ai/test`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: testMessage }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to run test."); setResult(body.result); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to run test."); } finally { setTesting(false); } }
  return <div className="ai-layout"><div className="ai-main">
    <section className="card card-pad"><div className="section-head compact"><div><h2>Behavior</h2><span className="muted">Customize sales behavior without changing protected reliability rules.</span></div><span className={`status-chip ${aiEnabled ? "green" : "gray"}`}><span className="dot" />AI {aiEnabled ? "Live" : "Paused"}</span></div><div className="settings-grid">
      <Select label="Language" value={value.language} options={[["auto","Auto"],["bangla","Bangla"],["banglish","Banglish"],["english","English"]]} onChange={(v) => set("language", v)} /><Select label="Tone" value={value.tone} options={[["natural_sales","Natural Sales"],["friendly","Friendly"],["formal","Formal"],["concise","Concise"]]} onChange={(v) => set("tone", v)} /><Select label="Reply length" value={value.replyLength} options={[["short","Short"],["medium","Medium"]]} onChange={(v) => set("replyLength", v)} /><Select label="Max products per recommendation" value={String(value.maxProductsPerRecommendation)} options={[["1","1"],["2","2"]]} onChange={(v) => set("maxProductsPerRecommendation", Number(v) as 1 | 2)} /><Select label="Model" value={value.modelOverride ?? "master"} options={[["master","Use Master"],["deepseek-v4-flash","V4 Flash"],["deepseek-v4-pro","V4 Pro"]]} onChange={(v) => set("modelOverride", v as Settings["modelOverride"])} /><Select label="Thinking" value={value.thinking ?? "master"} options={[["master","Use Master"],["off","Off"],["on","On where supported"]]} onChange={(v) => set("thinking", v as Settings["thinking"])} /><Select label="Max output tokens" value={String(value.maxOutputTokens ?? 700)} options={[["400","400"],["700","700"],["1200","1200"],["2000","2000"]]} onChange={(v) => set("maxOutputTokens", Number(v))} />
      <Toggle label="Understand the customer before recommending" value={value.understandBeforeRecommend} onChange={(v) => set("understandBeforeRecommend", v)} /><Toggle label="Suggest a combo when relevant" value={value.suggestCombo} onChange={(v) => set("suggestCombo", v)} /><Toggle label="Ask one useful question at a time" value={value.askOneQuestionAtATime} onChange={(v) => set("askOneQuestionAtATime", v)} /><Toggle label="Mirror the customer's language" value={value.mirrorCustomerLanguage} onChange={(v) => set("mirrorCustomerLanguage", v)} />
    </div></section>
    <section className="card card-pad"><h2>Memory</h2><p className="subtitle">Structured facts remain authoritative; rolling summaries never overwrite them.</p><div className="settings-grid" style={{ marginTop: 20 }}><Toggle label="Customer memory" value={value.customerMemory} onChange={(v) => set("customerMemory", v)} /><Select label="Recent message context" value={String(value.recentMessageContext)} options={[["10","10 messages"],["12","12 messages"],["16","16 messages"],["20","20 messages"]]} onChange={(v) => set("recentMessageContext", Number(v))} /><Toggle label="Rolling summary" value={value.rollingSummary} onChange={(v) => set("rollingSummary", v)} /></div><p className="field-hint" style={{ marginTop: 14 }}>Remembered: customer facts, needs, preferences, asked questions, recommendations, and previous orders.</p></section>
    <section className="card card-pad"><h2>Message handling</h2><div className="settings-grid" style={{ marginTop: 20 }}><Toggle label="Smart buffer" value={value.smartBuffer} onChange={(v) => set("smartBuffer", v)} /><Select label="Buffer window" value={String(value.bufferWindowSeconds)} options={[["3","3 seconds"],["8","8 seconds"],["15","15 seconds"],["30","30 seconds"]]} onChange={(v) => set("bufferWindowSeconds", Number(v))} /><Toggle label="Manual reply collision protection" value={value.manualCollisionProtection} onChange={(v) => set("manualCollisionProtection", v)} /><Select label="Manual activity cooldown" value={String(value.manualActivityCooldownSeconds)} options={[["10","10 seconds"],["30","30 seconds"],["60","60 seconds"],["120","120 seconds"]]} onChange={(v) => set("manualActivityCooldownSeconds", Number(v))} /></div><div className="locked-list"><span>Locked on · Avoid repeated questions</span><span>Locked on · Stale reply protection</span><span>Locked on · Sequential conversation processing</span></div></section>
    <section className="card card-pad"><h2>Sales instructions</h2><p className="subtitle">Page-specific strategy and tone. Protected platform rules always win.</p><textarea className="textarea small" style={{ marginTop: 18 }} value={value.customSalesInstructions} onChange={(e) => set("customSalesInstructions", e.target.value)} placeholder="Describe how this Page should guide customers…" /><div className="form-actions"><button className="button primary" onClick={save} disabled={loading}>{loading ? "Saving…" : "Save AI settings"}</button></div>{message && <div className="callout info" role="status" style={{ marginTop: 12 }}>{message}</div>}</section>
  </div><aside className="ai-side"><section className="card card-pad"><h2>Status</h2><div className="status-panel"><span className={`status-chip ${aiEnabled ? "green" : "gray"}`}><span className="dot" />AI {aiEnabled ? "Live" : "Paused"}</span><span className="field-hint">Core safety rules are always active.</span></div><div className="locked-list"><span>Never invent price or policy</span><span>Never recommend inactive products</span><span>Backend owns order state</span><span>Secrets never enter prompts</span></div></section><section className="card card-pad"><h2>Test AI</h2><p className="subtitle">Run a safe Page-scoped test. It never sends a Messenger reply.</p><textarea className="textarea small" style={{ marginTop: 16 }} value={testMessage} onChange={(e) => setTestMessage(e.target.value)} aria-label="Customer message" /><button className="button secondary full" style={{ marginTop: 10 }} onClick={runTest} disabled={testing || !testMessage.trim()}>{testing ? "Running…" : "Run test"}</button>{result && <div className="test-result" role="status"><div className="callout info"><span className="callout-icon">{result.label}</span><span>{result.reply}</span></div><dl><dt>Intent</dt><dd>{result.intent}</dd><dt>Products selected</dt><dd>{result.productsSelected.join(", ") || "None"}</dd><dt>Question key</dt><dd>{result.questionKey}</dd><dt>Validation</dt><dd>{result.validationResult}</dd><dt>Token usage</dt><dd>{result.tokenUsage.total}</dd><dt>Latency</dt><dd>{result.latencyMs} ms</dd></dl></div>}</section></aside></div>;
}

function Select({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><select className="input" value={value} onChange={(e) => onChange(e.target.value)}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <label className="setting-toggle"><span>{label}</span><button type="button" className={`toggle ${value ? "on" : ""}`} onClick={() => onChange(!value)} aria-pressed={value} aria-label={`${label}: ${value ? "on" : "off"}`} /></label>; }
