"use client";

import { useState } from "react";
import { UnsavedChangesGuard } from "@/components/common/unsaved-changes-guard";

type Values = { businessName: string; description: string; benefits: string; deliveryPolicy: string; codPolicy: string; faq: string; salesInstructions: string; notes: string; rawBusinessInfo: string };
export function BusinessEditor({ pageId, initial }: { pageId: string; initial: Values }) {
  const [value, setValue] = useState(initial); const [baseline, setBaseline] = useState(initial); const [message, setMessage] = useState(""); const [saved, setSaved] = useState(false); const [loading, setLoading] = useState(false); const dirty = JSON.stringify(value) !== JSON.stringify(baseline); const set = (key: keyof Values, input: string) => { setSaved(false); setValue((current) => ({ ...current, [key]: input })); };
  async function save() { setLoading(true); setMessage(""); const response = await fetch("/api/business", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageId, ...value }) }); const data = await response.json().catch(() => null); setLoading(false); if (!response.ok) { setMessage(data?.error ?? "Unable to save."); return; } setBaseline(value); setSaved(true); setMessage("Draft saved. Live configuration is unchanged."); }
  return <div className="grid grid-2"><UnsavedChangesGuard dirty={dirty} /><section className="card card-pad"><h2>Source information</h2><p className="subtitle">The raw source stays available for future AI parsing and manual review.</p><div className="field" style={{ marginTop: 22 }}><label htmlFor="raw">Tell us about this business</label><textarea className="textarea" id="raw" value={value.rawBusinessInfo} onChange={(e) => set("rawBusinessInfo", e.target.value)} placeholder="Products, prices, sizes, colors, benefits, delivery, COD, FAQ, policies…" /></div><div className="callout info"><span className="callout-icon">i</span><span>AI is never the business source of truth. Review and edit the structured fields before publishing.</span></div></section><section className="card card-pad"><h2>Structured business profile</h2><p className="subtitle">These editable fields are stored against this Page only.</p><div style={{ marginTop: 22 }}><Field label="Business name" value={value.businessName} onChange={(v) => set("businessName", v)} /><Field label="Description" value={value.description} onChange={(v) => set("description", v)} textarea /><Field label="Benefits (one per line)" value={value.benefits} onChange={(v) => set("benefits", v)} textarea /><Field label="Delivery policy" value={value.deliveryPolicy} onChange={(v) => set("deliveryPolicy", v)} textarea /><Field label="COD policy" value={value.codPolicy} onChange={(v) => set("codPolicy", v)} textarea /><Field label="FAQ" value={value.faq} onChange={(v) => set("faq", v)} textarea /><Field label="Sales instructions" value={value.salesInstructions} onChange={(v) => set("salesInstructions", v)} textarea /><Field label="Order requirements / notes" value={value.notes} onChange={(v) => set("notes", v)} textarea /></div>{message && <div className={saved ? "callout info" : "error-message"} style={{ marginTop: 10 }} role="status">{message}</div>}<div className="form-actions"><button className="button primary" onClick={() => void save()} disabled={loading || !dirty || value.rawBusinessInfo.trim().length < 10}>{loading ? "Saving…" : "Save as draft"}</button></div></section></div>;
}
function Field({ label, value, onChange, textarea }: { label: string; value: string; onChange: (v: string) => void; textarea?: boolean }) { return <div className="field"><label>{label}</label>{textarea ? <textarea className="textarea small" value={value} onChange={(e) => onChange(e.target.value)} /> : <input className="input" value={value} onChange={(e) => onChange(e.target.value)} />}</div>; }
