"use client";

import { useState } from "react";

const errors: Record<string, string> = { TOKEN_INVALID: "The Facebook Page Access Token is invalid.", PAGE_ID_MISMATCH: "The token does not belong to this Facebook Page.", APP_MISMATCH: "This token belongs to another Meta App.", PAGE_ALREADY_CONNECTED: "Facebook Page already connected", PERMISSION_ERROR: "This Page token does not have the required Messenger permissions.", WEBHOOK_ERROR: "Facebook webhook subscription could not be verified.", META_UNAVAILABLE: "Facebook could not be verified right now. Try again shortly.", TOKEN_REPLACEMENT_FAILED: "The replacement token could not be verified. The existing connection was preserved." };

export function ManualFacebookConnect({ existingPageId, onConnected }: { existingPageId?: string; onConnected: (page: { id: string; name: string }) => void }) {
  const [metaPageId, setMetaPageId] = useState(""); const [token, setToken] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<{ code?: string; message: string; slug?: string } | null>(null); const [success, setSuccess] = useState<{ id: string; name: string } | null>(null);
  async function submit() { setLoading(true); setError(null); setSuccess(null); try { const response = await fetch("/api/meta/manual-connect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ metaPageId: metaPageId.trim(), pageAccessToken: token, ...(existingPageId ? { existingPageId } : {}) }) }); const body = await response.json().catch(() => ({})); setToken(""); if (!response.ok) { setError({ code: body.status, message: errors[body.status] ?? "Facebook Page connection could not be completed.", slug: body.slug }); return; } const page = body.page as { id: string; name: string }; setSuccess(page); } catch { setToken(""); setError({ message: "Unable to reach the Facebook connection service." }); } finally { setLoading(false); } }
  return <section className="card card-pad"><div className="eyebrow">Connect</div><h2>{existingPageId ? "Replace Facebook Access Token" : "Connect Facebook Messenger"}</h2><p className="subtitle">Use the Page ID and Page Access Token from your Meta app/Page setup.</p><div className="form-grid" style={{ marginTop: 22 }}><label className="field"><span>Facebook Page ID</span><input className="input" value={metaPageId} onChange={(event) => setMetaPageId(event.target.value)} placeholder="123456789012345" inputMode="numeric" /></label><label className="field"><span>Page Access Token</span><input className="input" type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder="Paste Page Access Token" autoComplete="new-password" /></label></div><button className="button primary" onClick={() => void submit()} disabled={loading || !metaPageId.trim() || !token.trim()}>{loading ? "Verifying…" : "Verify & Connect"}</button>{loading && <div className="locked-list" style={{ marginTop: 16 }}><span>Verifying Page identity</span><span>Checking credential</span><span>Subscribing webhook</span></div>}{error && <div className="callout warning" role="alert" style={{ marginTop: 18 }}><strong>{error.message}</strong>{error.code === "PAGE_ALREADY_CONNECTED" && error.slug && <div className="form-actions"><a className="button secondary" href={`/pages/${error.slug}`}>Manage Page</a></div>}</div>}{success && <div className="callout info" role="status" style={{ marginTop: 18 }}><strong>✓ Page identity verified</strong><div className="locked-list" style={{ marginTop: 12 }}><span>✓ Token valid</span><span>✓ Meta App matched</span><span>✓ Webhook subscribed</span><span>✓ Messenger connected</span></div><p className="field-hint">Page Name · {success.name}</p><button className="button primary" onClick={() => onConnected(success)}>Continue to Business</button></div>}<details style={{ marginTop: 26 }}><summary><strong>Advanced connection methods</strong></summary><div className="card card-pad" style={{ marginTop: 14 }}><h3>Connect automatically with Facebook</h3><p className="field-hint">Beta / Advanced · uses Facebook OAuth and Page discovery.</p><a className="button secondary" href="/api/meta/oauth/start">Continue with Facebook</a></div></details></section>;
}
