"use client";

import { useState } from "react";

type Fact = { id: string; factKey: string; displayValue: string | null; normalizedValue: unknown; status: string; lastConfirmedAt: string | Date | null; sourceType: string; updatedAt: string | Date; supersededByFactId?: string | null };
type Order = { id: string; orderSessionId: string; status: string; total: number | string | null; currency?: string | null; productName?: string | null; quantity?: number | null; createdAt: string | Date; confirmedAt?: string | Date | null };
type MemoryData = { pageId: string; customerId: string; memory: { knownFacts: Record<string, unknown>; unconfirmedFacts: Record<string, unknown>; needs: string[]; preferences: Record<string, unknown>; semanticQuestionsAsked: string[]; recommendedProductIds: string[]; rejectedProductIds: string[]; activeOrderReference: string | null; summary: string }; facts: Fact[]; summaryStale?: boolean; summaryVersion?: number; orders: Order[] };

export function MemoryInspector({ pageId, customerId, initial }: { pageId: string; customerId: string; initial: MemoryData }) {
  const [data, setData] = useState(initial);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [editor, setEditor] = useState<{ factKey: string; value: string } | null>(null);
  const [confirm, setConfirm] = useState<{ action: "markUnknown" | "remove" | "clearNonOrderMemory"; factKey?: string } | null>(null);
  const factEntries = [...new Set([...Object.keys(data.memory.knownFacts), ...Object.keys(data.memory.unconfirmedFacts)])].map((key) => [key, data.memory.knownFacts[key] ?? data.memory.unconfirmedFacts[key]] as const);
  async function mutate(action: string, factKey?: string, value?: string) {
    setBusy(true); setMessage(null);
    try {
      const response = await fetch(`/api/pages/${pageId}/customers/${customerId}/memory`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, factKey, value }) });
      const body = await response.json().catch(() => null);
      if (!response.ok) throw new Error(body?.error ?? "Memory action failed.");
      setData(body.data); setMessage("Memory updated."); setEditor(null); setConfirm(null);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Memory action failed."); }
    finally { setBusy(false); }
  }
  function date(value: string | Date | null | undefined) { return value ? new Date(value).toLocaleString() : "—"; }
  return <div className="grid" style={{ gap: 20 }}>
    {message && <div className="callout info" role="status">{message}</div>}
    <section className="card card-pad"><div className="section-head inline-head"><div><h2>Memory</h2><span className="muted">Structured facts are authoritative; the summary is only a bounded convenience.</span></div><span className={`status-chip ${data.summaryStale ? "amber" : "green"}`}><span className="dot" />Summary {data.summaryStale ? "stale" : "current"}</span></div><div className="grid grid-2" style={{ marginTop: 18 }}><MemoryList title="Needs" values={data.memory.needs} /><MemoryList title="Preferences" values={Object.entries(data.memory.preferences).map(([key, value]) => `${key}: ${String(value)}`)} /><MemoryList title="Asked Question Keys" values={data.memory.semanticQuestionsAsked} /><MemoryList title="Recommended Products" values={data.memory.recommendedProductIds} /><MemoryList title="Rejected Products" values={data.memory.rejectedProductIds} /><div><div className="metric-label">Active Order Reference</div><div style={{ marginTop: 8, fontSize: 13 }}>{data.memory.activeOrderReference ?? "None"}</div></div></div></section>
    <section className="card card-pad"><div className="section-head inline-head"><div><h2>Known Facts</h2><span className="muted">Status, confirmation time, and source stay visible for each structured fact.</span></div></div>{factEntries.length === 0 && <p className="empty-inline">No known facts.</p>}{factEntries.length > 0 && <div className="table-wrap"><table><thead><tr><th>Fact key</th><th>Display value</th><th>Status</th><th>Last confirmed</th><th>Source type</th><th /></tr></thead><tbody>{factEntries.map(([key, value]) => { const fact = data.facts.find((item) => item.factKey === key && ["ACTIVE", "UNCONFIRMED"].includes(item.status)); return <tr key={key}><td>{key}</td><td>{String(value)}</td><td>{fact?.status ?? "UNCONFIRMED"}</td><td>{date(fact?.lastConfirmedAt)}</td><td>{fact?.sourceType ?? "—"}</td><td><div className="row-actions"><button className="text-button" disabled={busy} onClick={() => setEditor({ factKey: key, value: String(value) })}>Edit</button><button className="text-button danger-text" disabled={busy} onClick={() => setConfirm({ action: "markUnknown", factKey: key })}>Unknown</button><button className="text-button danger-text" disabled={busy} onClick={() => setConfirm({ action: "remove", factKey: key })}>Remove</button></div></td></tr>; })}</tbody></table></div>}</section>
    <section className="card card-pad"><div className="section-head inline-head"><h2>Previous Orders</h2><span className="muted">Order history is preserved outside non-order memory actions.</span></div>{data.orders.length === 0 ? <p className="empty-inline">No previous orders.</p> : <div className="table-wrap"><table><thead><tr><th>Order</th><th>Product</th><th>Status</th><th>Total</th><th>Created</th></tr></thead><tbody>{data.orders.map((order) => <tr key={order.id}><td>{order.id.slice(0, 8)}</td><td>{order.productName ?? "—"}{order.quantity ? ` × ${order.quantity}` : ""}</td><td>{order.status}</td><td>{order.total == null ? "—" : `${order.currency ?? ""} ${order.total}`}</td><td>{date(order.createdAt)}</td></tr>)}</tbody></table></div>}</section>
    <details className="card card-pad"><summary style={{ cursor: "pointer", fontWeight: 700 }}>Advanced</summary><div className="form-actions" style={{ marginTop: 16 }}><button className="button secondary" disabled={busy} onClick={() => void mutate("rebuildSummary")}>Rebuild Summary</button><button className="button danger" disabled={busy} onClick={() => setConfirm({ action: "clearNonOrderMemory" })}>Clear Non-Order Memory</button></div><pre style={{ overflowX: "auto", whiteSpace: "pre-wrap", color: "var(--muted)", fontSize: 11, marginTop: 16 }}>{JSON.stringify({ summary: data.memory.summary, summaryVersion: data.summaryVersion, facts: data.facts }, null, 2)}</pre></details>
    {editor && <div className="confirm-popover" role="dialog" aria-modal="true" aria-label="Edit fact" style={{ position: "fixed", right: 24, bottom: 24, top: "auto", minWidth: 300 }}><strong>Edit {editor.factKey}</strong><input className="input" value={editor.value} onChange={(event) => setEditor({ ...editor, value: event.target.value })} /><div><button className="button secondary" onClick={() => setEditor(null)}>Cancel</button><button className="button primary" disabled={busy || !editor.value.trim()} onClick={() => void mutate("edit", editor.factKey, editor.value)}>Save</button></div></div>}
    {confirm && <div className="confirm-popover" role="dialog" aria-modal="true" aria-label="Confirm memory action" style={{ position: "fixed", right: 24, bottom: 24, top: "auto", minWidth: 330 }}><strong>{confirm.action === "clearNonOrderMemory" ? "Clear non-order memory?" : confirm.action === "markUnknown" ? "Mark this fact unknown?" : "Remove this fact?"}</strong><p className="field-hint">This action is Page and customer scoped. Historical fact records remain available where supported. Order history is not deleted.</p><div><button className="button secondary" onClick={() => setConfirm(null)}>Cancel</button><button className="button danger" disabled={busy} onClick={() => void mutate(confirm.action, confirm.factKey)}>Confirm</button></div></div>}
  </div>;
}

function MemoryList({ title, values }: { title: string; values: string[] }) { return <div><div className="metric-label">{title}</div>{values.length ? <div className="locked-list">{values.map((value) => <span key={value}>{value}</span>)}</div> : <div className="empty-inline">None</div>}</div>; }
