"use client";

import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

type Setup = { pageId: string; pageName: string; rawBusinessInfo: string; businessName: string; description: string; benefits: string; deliveryPolicy: string; codPolicy: string; faq: string; salesInstructions: string; notes: string };
type MetaPage = { id: string; name: string };
type Parsed = { business_profile: { business_name: string | null; description: string | null; benefits: string[] }; products: Array<{ name: string; description: string; variants: Array<{ sku: string; size: string | null; current_price: number }> }>; policies: { delivery: string | null; cod: string | null; faq: string[] }; sales_instructions: string | null; order_requirements: string[]; unknown_information: string[]; conflicts: string[] };
const initial: Setup = { pageId: "", pageName: "", rawBusinessInfo: "", businessName: "", description: "", benefits: "", deliveryPolicy: "", codPolicy: "", faq: "", salesInstructions: "", notes: "" };

export function OnboardingWizard({ previewMode = false }: { previewMode?: boolean }) {
  const router = useRouter();
  const [step, setStep] = useState(1); const [setup, setSetup] = useState(initial); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [available, setAvailable] = useState<MetaPage[]>([]); const [chooserOpen, setChooserOpen] = useState(false); const [analysis, setAnalysis] = useState<Parsed | null>(null);
  const set = (key: keyof Setup, value: string) => setSetup((current) => ({ ...current, [key]: value }));
  useEffect(() => { if (!previewMode) { const state = new URLSearchParams(window.location.search).get("meta_state"); if (state) void loadProductionPages(state); } else { void loadPreviewPages(); } }, [previewMode]);
  async function loadPreviewPages() { const response = await fetch("/api/meta/pages?state=preview"); const body = await response.json(); if (response.ok) setAvailable(body.pages); }
  async function loadProductionPages(state: string) { setLoading(true); const response = await fetch(`/api/meta/pages?state=${encodeURIComponent(state)}`); const body = await response.json(); if (response.ok) setAvailable(body.pages); else setMessage(body.error ?? "Unable to discover Facebook Pages."); setLoading(false); }
  async function connect(metaPage: MetaPage) { setLoading(true); setMessage(""); const created = await fetch("/api/pages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: metaPage.name }) }); const createdData = await created.json(); if (!created.ok) { setLoading(false); return setMessage(createdData.error ?? "Unable to create the Page workspace."); } const state = previewMode ? undefined : new URLSearchParams(window.location.search).get("meta_state") ?? undefined; const response = await fetch("/api/meta/connect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageId: createdData.id, metaPageId: metaPage.id, ...(state ? { state } : {}) }) }); const data = await response.json(); setLoading(false); if (!response.ok) return setMessage(data.error ?? "Unable to connect the Page."); setSetup((current) => ({ ...current, pageId: createdData.id, pageName: metaPage.name })); setChooserOpen(false); setStep(2); }
  async function analyze() { setLoading(true); setMessage(""); const response = await fetch("/api/business/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageId: setup.pageId, rawBusinessInfo: setup.rawBusinessInfo }) }); const body = await response.json(); setLoading(false); if (!response.ok) return setMessage(body.error ?? "Unable to analyze the business."); const parsed = body.result as Parsed; setAnalysis(parsed); setSetup((current) => ({ ...current, businessName: parsed.business_profile.business_name ?? current.businessName, description: parsed.business_profile.description ?? current.description, benefits: parsed.business_profile.benefits.join("\n"), deliveryPolicy: parsed.policies.delivery ?? "", codPolicy: parsed.policies.cod ?? "", faq: parsed.policies.faq.join("\n"), salesInstructions: parsed.sales_instructions ?? "", notes: parsed.order_requirements.join("\n") })); }
  async function saveDraft() { setLoading(true); setMessage(""); const response = await fetch("/api/business", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(setup) }); const body = await response.json(); setLoading(false); if (!response.ok) return setMessage(body.error ?? "Unable to save the draft."); setStep(3); }
  return <><div className="stepper"><Step number="1" label="Connect" active={step === 1} done={step > 1} /><Step number="2" label="Business" active={step === 2} done={step > 2} /><Step number="3" label="Go Live" active={step === 3} done={false} /></div>{message && <div className="error-message" style={{ maxWidth: 760, margin: "0 auto 18px" }} role="alert">{message}</div>}{step === 1 && <ConnectStep loading={loading} pages={available} previewMode={previewMode} chooserOpen={chooserOpen} setChooserOpen={setChooserOpen} onConnect={connect} />} {step === 2 && <BusinessStep setup={setup} set={set} loading={loading} analysis={analysis} analyze={analyze} saveDraft={saveDraft} onBack={() => setStep(1)} />} {step === 3 && <ReviewStep setup={setup} previewMode={previewMode} loading={loading} onBack={() => setStep(2)} onLive={() => router.push(`/pages/${setup.pageId}`)} />}</>;
}

function ConnectStep({ loading, pages, previewMode, chooserOpen, setChooserOpen, onConnect }: { loading: boolean; pages: MetaPage[]; previewMode: boolean; chooserOpen: boolean; setChooserOpen: (open: boolean) => void; onConnect: (page: MetaPage) => Promise<void> }) { const [selected, setSelected] = useState(""); const selectedPage = pages.find((page) => page.id === selected); return <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Connect</div><h2>Connect Facebook Page</h2><p className="subtitle">{previewMode ? "Choose a local Page to preview the complete onboarding flow." : "Authorize Facebook, choose a Page you manage, and verify the connection."}</p>{previewMode ? <><div className="callout info" style={{ margin: "22px 0" }}><span className="callout-icon">i</span><span>Preview mode uses a local Facebook adapter. No Meta request or OAuth validation is performed.</span></div><button className="button primary" onClick={() => setChooserOpen(true)}>Continue with Facebook</button>{chooserOpen && <div className="chooser-drawer" role="dialog" aria-label="Available Pages"><div className="drawer-head"><div><h3>Available Pages</h3><p className="field-hint">Select one Page to connect.</p></div><button className="button ghost" onClick={() => setChooserOpen(false)}>Close</button></div><div className="page-choice-list">{pages.map((page) => <label className="page-choice" key={page.id}><input type="radio" name="preview-page" value={page.id} checked={selected === page.id} onChange={() => setSelected(page.id)} /><span>{page.name}</span></label>)}</div><button className="button primary full" disabled={!selectedPage || loading} onClick={() => selectedPage && void onConnect(selectedPage)}>{loading ? "Connecting…" : "Connect Page"}</button></div>}</> : <><a className="button primary" href="/api/meta/oauth/start">{loading ? "Loading…" : "Continue with Facebook"}</a>{pages.length > 0 && <div className="field" style={{ marginTop: 22 }}><label>Available Facebook Pages</label><select className="input" defaultValue="" onChange={(event) => { const page = pages.find((candidate) => candidate.id === event.target.value); if (page) void onConnect(page); }}><option value="" disabled>Select a Page</option>{pages.map((page) => <option value={page.id} key={page.id}>{page.name}</option>)}</select></div>}</>}</section><Aside title="A simple start"><p>Each connected Page gets its own isolated business, products, customers, conversations, and configuration.</p></Aside></div>; }
function BusinessStep({ setup, set, loading, analysis, analyze, saveDraft, onBack }: { setup: Setup; set: (key: keyof Setup, value: string) => void; loading: boolean; analysis: Parsed | null; analyze: () => Promise<void>; saveDraft: () => Promise<void>; onBack: () => void }) { return <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Business</div><h2>Tell us about this business</h2><p className="subtitle">Analyze the notes, then review and edit every structured field before going live.</p><div className="field" style={{ marginTop: 22 }}><label htmlFor="rawBusinessInfo">Business information <span className="required">*</span></label><textarea className="textarea" id="rawBusinessInfo" value={setup.rawBusinessInfo} onChange={(e) => set("rawBusinessInfo", e.target.value)} placeholder="Products, prices, delivery, COD, FAQ, policies, and sales instructions" /></div><button className="button secondary" onClick={() => void analyze()} disabled={loading || setup.rawBusinessInfo.trim().length < 10}>{loading ? "Analyzing…" : "Analyze Business"}</button>{analysis && <div className="analysis-result"><h3>Structured result</h3><p><strong>Business:</strong> {analysis.business_profile.business_name}</p><p><strong>Products:</strong> {analysis.products.map((product) => product.name).join(", ")}</p><p><strong>Policies:</strong> {analysis.policies.delivery}</p><p><strong>Order requirements:</strong> {analysis.order_requirements.join(", ")}</p><p><strong>Unknown information:</strong> {analysis.unknown_information.join(", ") || "None"}</p></div>}<div className="grid grid-2" style={{ marginTop: 20 }}><Field label="Business name" value={setup.businessName} onChange={(v) => set("businessName", v)} /><Field label="Short description" value={setup.description} onChange={(v) => set("description", v)} /></div><Field label="Benefits (one per line)" value={setup.benefits} onChange={(v) => set("benefits", v)} textarea /><div className="grid grid-2"><Field label="Delivery policy" value={setup.deliveryPolicy} onChange={(v) => set("deliveryPolicy", v)} textarea /><Field label="COD policy" value={setup.codPolicy} onChange={(v) => set("codPolicy", v)} textarea /><Field label="FAQ" value={setup.faq} onChange={(v) => set("faq", v)} textarea /><Field label="Sales instructions" value={setup.salesInstructions} onChange={(v) => set("salesInstructions", v)} textarea /></div><Field label="Order requirements / custom knowledge" value={setup.notes} onChange={(v) => set("notes", v)} textarea /><div className="form-actions"><button className="button secondary" onClick={onBack}>Back</button><button className="button primary" onClick={() => void saveDraft()} disabled={loading || setup.rawBusinessInfo.trim().length < 10}>{loading ? "Saving…" : "Continue to review"}</button></div></section><Aside title="Draft first"><p>Analysis creates a structured draft. Live configuration stays unchanged until the final action.</p></Aside></div>; }
function ReviewStep({ setup, previewMode, loading, onBack, onLive }: { setup: Setup; previewMode: boolean; loading: boolean; onBack: () => void; onLive: () => void }) { const [error, setError] = useState(""); const [checks, setChecks] = useState<Array<{ label: string; ok: boolean; detail: string }>>([]); useEffect(() => { void fetch(`/api/pages/${setup.pageId}/readiness`).then(async (response) => { const body = await response.json(); if (response.ok) setChecks(body.checks); }); }, [setup.pageId]); async function goLive() { setError(""); if (previewMode) { const published = await fetch("/api/config/publish", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageId: setup.pageId }) }); if (!published.ok) { const body = await published.json().catch(() => null); setError(body?.error ?? "Business draft could not be published."); return; } } const response = await fetch(`/api/pages/${setup.pageId}/go-live`, { method: "POST" }); if (response.ok) onLive(); else { const body = await response.json().catch(() => null); setError(body?.error ?? "Unable to go live."); } } const ready = checks.length === 0 || checks.every((check) => check.ok); return <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Go Live</div><h2>Review & Go Live</h2><p className="subtitle">Review the operational checklist before publishing this Page configuration.</p><div className="review-block"><h3>Connected Page</h3><div className="review-value">{setup.pageName}</div></div><div className="review-block"><h3>Business</h3><div className="review-value">{setup.businessName || "Business profile ready"}</div></div>{checks.length > 0 && <div className="readiness-list">{checks.map((check) => <div className="readiness-row" key={check.label}><span className={`status-chip ${check.ok ? "green" : "amber"}`}><span className="dot" />{check.ok ? "READY" : "NEEDS ATTENTION"}</span><span>{check.label}</span>{!check.ok && <small>{check.detail}</small>}</div>)}</div>}{error && <div className="error-message" role="alert">{error}</div>}<div className="form-actions"><button className="button secondary" onClick={onBack}>Back to edit</button><button className="button primary" onClick={() => void goLive()} disabled={loading || !ready}>{loading ? "Publishing…" : "Go Live"}</button></div></section><Aside title="Operational checklist"><p>Facebook</p><p>Business and products</p><p>AI and Telegram</p><p>Memory, orders, and budget</p></Aside></div>; }
function Step({ number, label, active, done }: { number: string; label: string; active: boolean; done: boolean }) { return <div className={`step ${active ? "active" : ""} ${done ? "done" : ""}`}><div className="step-number">{done ? "✓" : number}</div>{label}</div>; }
function Aside({ title, children }: { title: string; children: React.ReactNode }) { return <aside className="card card-pad"><h3>{title}</h3><div className="subtitle" style={{ display: "grid", gap: 15, marginTop: 15 }}>{children}</div></aside>; }
function Field({ label, value, onChange, textarea }: { label: string; value: string; onChange: (value: string) => void; textarea?: boolean }) { return <div className="field"><label>{label}</label>{textarea ? <textarea className="textarea small" value={value} onChange={(e) => onChange(e.target.value)} /> : <input className="input" value={value} onChange={(e) => onChange(e.target.value)} />}</div>; }
