"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Setup = { pageId: string; pageName: string; rawBusinessInfo: string; businessName: string; description: string; benefits: string; deliveryPolicy: string; codPolicy: string; faq: string; salesInstructions: string; notes: string };
type MetaPage = { id: string; name: string };
const initial: Setup = { pageId: "", pageName: "", rawBusinessInfo: "", businessName: "", description: "", benefits: "", deliveryPolicy: "", codPolicy: "", faq: "", salesInstructions: "", notes: "" };

export function OnboardingWizard({ previewMode = false }: { previewMode?: boolean }) {
  const [step, setStep] = useState(1); const [setup, setSetup] = useState(initial); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [metaState, setMetaState] = useState(""); const [metaPages, setMetaPages] = useState<MetaPage[]>([]);
  const set = (key: keyof Setup, value: string) => setSetup((current) => ({ ...current, [key]: value }));
  useEffect(() => { const state = new URLSearchParams(window.location.search).get("meta_state"); if (!state) return; setMetaState(state); setLoading(true); fetch(`/api/meta/pages?state=${encodeURIComponent(state)}`).then(async (response) => { const data = await response.json(); if (!response.ok) setMessage(data.error ?? "Unable to discover Pages."); else setMetaPages(data.pages); }).catch(() => setMessage("Unable to discover Pages.")).finally(() => setLoading(false)); }, []);
  async function connect(metaPageId: string, name: string) { setLoading(true); setMessage(""); const created = await fetch("/api/pages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const createdData = await created.json(); if (!created.ok) { setLoading(false); return setMessage(createdData.error ?? "Unable to create the Page workspace."); } const response = await fetch("/api/meta/connect", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageId: createdData.id, metaPageId, state: metaState }) }); const data = await response.json(); setLoading(false); if (!response.ok) return setMessage(data.error ?? "Unable to connect the Page."); setSetup((current) => ({ ...current, pageId: createdData.id, pageName: name })); setStep(2); }
  async function saveDraft() { setLoading(true); setMessage(""); const response = await fetch("/api/business", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(setup) }); const data = await response.json(); setLoading(false); if (!response.ok) return setMessage(data.error ?? "Unable to save the draft."); setStep(3); }
  return <><div className="stepper"><Step number="1" label="Connect Facebook Page" active={step === 1} done={step > 1} /><Step number="2" label="Business Setup" active={step === 2} done={step > 2} /><Step number="3" label="Review & Go Live" active={step === 3} done={false} /></div>{message && <div className="error-message" style={{ maxWidth: 760, margin: "0 auto 18px" }}>{message}</div>}{step === 1 && <ConnectStep loading={loading} pages={metaPages} previewMode={previewMode} onConnect={connect} />} {step === 2 && <BusinessStep setup={setup} set={set} loading={loading} saveDraft={saveDraft} />} {step === 3 && <ReviewStep setup={setup} previewMode={previewMode} onBack={() => setStep(2)} />}</>;
}
function ConnectStep({ loading, pages, previewMode, onConnect }: { loading: boolean; pages: MetaPage[]; previewMode: boolean; onConnect: (id: string, name: string) => Promise<void> }) { return <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Step 1 of 3</div><h2>Connect Facebook Page</h2><p className="subtitle">{previewMode ? "Use a safe local fixture to preview the complete onboarding flow." : "Authorize Facebook, choose a Page you manage, and let the system verify the connection."}</p>{previewMode ? <><div className="callout info" style={{ margin: "22px 0" }}><span className="callout-icon">i</span><span>Facebook is mocked in development preview mode. No Meta credentials or network connection are used.</span></div><div className="form-actions"><Link className="button secondary" href="/pages">Cancel</Link><button className="button primary" onClick={() => void onConnect("preview-meta-page-001", "Growthifyx Demo Page")} disabled={loading}>{loading ? "Connecting…" : "Use mock Facebook Page"}</button></div></> : pages.length === 0 ? <><div className="callout info" style={{ margin: "22px 0" }}><span className="callout-icon">i</span><span>No Page access token, webhook URL, verify token, or Graph API URL is entered here.</span></div><div className="form-actions"><Link className="button secondary" href="/pages">Cancel</Link><a className="button primary" href="/api/meta/oauth/start">{loading ? "Loading..." : "Connect My Facebook"}</a></div></> : <div className="field"><label htmlFor="meta-page">Choose a Page</label><select className="input" id="meta-page" defaultValue="" onChange={(event) => { const page = pages.find((candidate) => candidate.id === event.target.value); if (page) void onConnect(page.id, page.name); }}><option value="" disabled>Select a Page</option>{pages.map((page) => <option value={page.id} key={page.id}>{page.name}</option>)}</select><span className="field-hint">Meta Page ID is the external identity; the display name is only a label.</span></div>}</section><Aside title="What happens next"><p>Your selected Page gets its own isolated settings, products, customers, conversations, and configuration versions.</p><p>The Page starts with AI paused until you explicitly enable it after review.</p></Aside></div>; }
function Step({ number, label, active, done }: { number: string; label: string; active: boolean; done: boolean }) { return <div className={`step ${active ? "active" : ""} ${done ? "done" : ""}`}><div className="step-number">{done ? "✓" : number}</div>{label}</div>; }
function Aside({ title, children }: { title: string; children: React.ReactNode }) { return <aside className="card card-pad"><h3>{title}</h3><div className="subtitle" style={{ display: "grid", gap: 15, marginTop: 15 }}>{children}</div></aside>; }
function BusinessStep({ setup, set, loading, saveDraft }: { setup: Setup; set: (key: keyof Setup, value: string) => void; loading: boolean; saveDraft: () => Promise<void> }) { return <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Step 2 of 3</div><h2>Tell us about this business</h2><p className="subtitle">Save raw business information and review the structured draft before publishing.</p><div className="field" style={{ marginTop: 22 }}><label htmlFor="rawBusinessInfo">Business information <span style={{ color: "var(--red)" }}>*</span></label><textarea className="textarea" id="rawBusinessInfo" value={setup.rawBusinessInfo} onChange={(e) => set("rawBusinessInfo", e.target.value)} placeholder="Products, prices, delivery, COD, FAQ, policies, sales instructions, and order requirements..." /></div><div className="grid grid-2"><Field label="Business name" value={setup.businessName} onChange={(v) => set("businessName", v)} /><Field label="Short description" value={setup.description} onChange={(v) => set("description", v)} /></div><div className="grid grid-2"><Field label="Benefits (one per line)" value={setup.benefits} onChange={(v) => set("benefits", v)} textarea /><Field label="Delivery policy" value={setup.deliveryPolicy} onChange={(v) => set("deliveryPolicy", v)} textarea /></div><div className="grid grid-2"><Field label="COD policy" value={setup.codPolicy} onChange={(v) => set("codPolicy", v)} textarea /><Field label="FAQ" value={setup.faq} onChange={(v) => set("faq", v)} textarea /></div><div className="grid grid-2"><Field label="Sales instructions" value={setup.salesInstructions} onChange={(v) => set("salesInstructions", v)} textarea /><Field label="Order requirements / notes" value={setup.notes} onChange={(v) => set("notes", v)} textarea /></div><div className="form-actions"><button className="button secondary" onClick={() => window.history.back()}>Back</button><button className="button primary" onClick={saveDraft} disabled={loading || setup.rawBusinessInfo.trim().length < 10}>{loading ? "Saving draft..." : "Save draft & review"}</button></div></section><Aside title="Draft first"><p>Editing this information creates a new DRAFT configuration version.</p><p>Live configuration remains unchanged until an explicit publish action.</p></Aside></div>; }
function Field({ label, value, onChange, textarea }: { label: string; value: string; onChange: (value: string) => void; textarea?: boolean }) { return <div className="field"><label>{label}</label>{textarea ? <textarea className="textarea small" value={value} onChange={(e) => onChange(e.target.value)} /> : <input className="input" value={value} onChange={(e) => onChange(e.target.value)} />}</div>; }
function ReviewStep({ setup, previewMode, onBack }: { setup: Setup; previewMode: boolean; onBack: () => void }) { const [live, setLive] = useState(false); const [error, setError] = useState(""); async function goLive() { setError(""); const response = await fetch(`/api/pages/${setup.pageId}/go-live`, { method: "POST" }); if (response.ok) setLive(true); else { const body = await response.json().catch(() => null); setError(body?.error ?? "Unable to go live."); } } return <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Step 3 of 3</div><h2>Review & Go Live</h2><p className="subtitle">Review the draft before publishing. Live configuration is unchanged until you explicitly publish it.</p><div className="callout warning" style={{ margin: "22px 0" }}><span className="callout-icon">!</span><span>Critical business conflicts must be resolved before publishing.</span></div><div className="review-block"><h3>Page</h3><div className="review-value">{setup.pageName}</div></div><div className="review-block"><h3>Business information</h3><div className="review-value">{setup.rawBusinessInfo}</div></div><div className="grid grid-2"><Review label="Business name" value={setup.businessName || "Not set"} /><Review label="Benefits" value={setup.benefits || "Not set"} /><Review label="Delivery" value={setup.deliveryPolicy || "Not set"} /><Review label="COD" value={setup.codPolicy || "Not set"} /></div>{error && <div className="error-message" role="alert">{error}</div>}{live && <div className="callout info" role="status">Preview Page is live. Production go-live still uses real readiness checks.</div>}<div className="form-actions"><button className="button secondary" onClick={onBack}>Back to edit</button>{previewMode && !live && <button className="button primary" onClick={goLive}>Go Live</button>}<Link className="button secondary" href={`/pages/${setup.pageId}`}>Open page workspace</Link></div></section><Aside title="Ready for review"><p>Draft configuration created successfully.</p><span className={`status-chip ${live ? "green" : "gray"}`}><span className="dot" /> {live ? "Live preview" : "Draft - not live"}</span></Aside></div>; }
function Review({ label, value }: { label: string; value: string }) { return <div className="review-block"><h3>{label}</h3><div className="review-value">{value}</div></div>; }
