"use client";

import Link from "next/link";
import { useState } from "react";

type Setup = { pageId: string; pageName: string; rawBusinessInfo: string; businessName: string; description: string; benefits: string; deliveryPolicy: string; codPolicy: string; faq: string; salesInstructions: string; notes: string };
const initial: Setup = { pageId: "", pageName: "", rawBusinessInfo: "", businessName: "", description: "", benefits: "", deliveryPolicy: "", codPolicy: "", faq: "", salesInstructions: "", notes: "" };

export function OnboardingWizard() {
  const [step, setStep] = useState(1); const [setup, setSetup] = useState(initial); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const set = (key: keyof Setup, value: string) => setSetup((current) => ({ ...current, [key]: value }));
  async function connect() { if (!setup.pageName.trim()) return setMessage("Enter a page name to continue."); setLoading(true); const response = await fetch("/api/pages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: setup.pageName }) }); const data = await response.json(); setLoading(false); if (!response.ok) return setMessage(data.error ?? "Unable to create the page."); setSetup((current) => ({ ...current, pageId: data.id })); setStep(2); }
  async function saveDraft() { setLoading(true); setMessage(""); const response = await fetch("/api/business", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(setup) }); const data = await response.json(); setLoading(false); if (!response.ok) return setMessage(data.error ?? "Unable to save the draft."); setStep(3); }
  return <>
    <div className="stepper"><Step number="1" label="Connect Facebook Page" active={step === 1} done={step > 1} /><Step number="2" label="Business Setup" active={step === 2} done={step > 2} /><Step number="3" label="Review & Go Live" active={step === 3} done={false} /></div>
    {message && <div className="error-message" style={{ maxWidth: 760, margin: "0 auto 18px" }}>{message}</div>}
    {step === 1 && <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Step 1 of 3</div><h2>Connect Facebook Page</h2><p className="subtitle">The Meta integration is intentionally staged for Step 2. For now, create the isolated page workspace you will connect later.</p><div className="callout info" style={{ margin: "22px 0" }}><span className="callout-icon">i</span><span>No Facebook credentials are requested or stored in Step 1. This is the future Meta module boundary.</span></div><div className="field"><label htmlFor="pageName">Page name</label><input className="input" id="pageName" value={setup.pageName} onChange={(e) => set("pageName", e.target.value)} placeholder="e.g. Acme Home" autoFocus /><span className="field-hint">This is a display label only. Meta Page ID will be the external identity when connected.</span></div><div className="form-actions"><Link className="button secondary" href="/pages">Cancel</Link><button className="button primary" onClick={connect} disabled={loading}>{loading ? "Creating…" : "Continue to business setup →"}</button></div></section><Aside title="What happens next"><p>Your page gets its own settings, products, customers, conversations, and configuration versions.</p><p>The page starts with AI paused until you explicitly enable it after review.</p></Aside></div>}
    {step === 2 && <BusinessStep setup={setup} set={set} loading={loading} saveDraft={saveDraft} />}
    {step === 3 && <ReviewStep setup={setup} onBack={() => setStep(2)} />}
  </>;
}

function Step({ number, label, active, done }: { number: string; label: string; active: boolean; done: boolean }) { return <div className={`step ${active ? "active" : ""} ${done ? "done" : ""}`}><div className="step-number">{done ? "✓" : number}</div>{label}</div>; }
function Aside({ title, children }: { title: string; children: React.ReactNode }) { return <aside className="card card-pad"><h3>{title}</h3><div className="subtitle" style={{ display: "grid", gap: 15, marginTop: 15 }}>{children}</div></aside>; }
function BusinessStep({ setup, set, loading, saveDraft }: { setup: Setup; set: (key: keyof Setup, value: string) => void; loading: boolean; saveDraft: () => Promise<void> }) { return <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Step 2 of 3</div><h2>Tell us about this business</h2><p className="subtitle">Save the raw business information first, then keep the important structured fields editable. AI parsing will be added in Step 2 of development.</p><div className="field" style={{ marginTop: 22 }}><label htmlFor="rawBusinessInfo">Business information <span style={{ color: "var(--red)" }}>*</span></label><textarea className="textarea" id="rawBusinessInfo" value={setup.rawBusinessInfo} onChange={(e) => set("rawBusinessInfo", e.target.value)} placeholder="Products, prices, sizes, colors, benefits, delivery, COD, FAQ, policies, sales instructions, order requirements, and any other notes…" /></div><div className="grid grid-2"><Field label="Business name" value={setup.businessName} onChange={(v) => set("businessName", v)} placeholder="Optional" /><Field label="Short description" value={setup.description} onChange={(v) => set("description", v)} placeholder="Optional" /></div><div className="grid grid-2"><Field label="Benefits (one per line)" value={setup.benefits} onChange={(v) => set("benefits", v)} textarea /><Field label="Delivery policy" value={setup.deliveryPolicy} onChange={(v) => set("deliveryPolicy", v)} textarea /></div><div className="grid grid-2"><Field label="COD policy" value={setup.codPolicy} onChange={(v) => set("codPolicy", v)} textarea /><Field label="FAQ" value={setup.faq} onChange={(v) => set("faq", v)} textarea /></div><div className="grid grid-2"><Field label="Sales instructions" value={setup.salesInstructions} onChange={(v) => set("salesInstructions", v)} textarea /><Field label="Order requirements / notes" value={setup.notes} onChange={(v) => set("notes", v)} textarea /></div><div className="form-actions"><button className="button secondary" onClick={() => window.history.back()}>Back</button><button className="button primary" onClick={saveDraft} disabled={loading || setup.rawBusinessInfo.trim().length < 10}>{loading ? "Saving draft…" : "Save draft & review →"}</button></div></section><Aside title="Draft first"><p>Editing this information creates a new DRAFT configuration version.</p><p>Live configuration remains unchanged until an explicit publish action.</p><span className="status-chip amber"><span className="dot" /> AI parsing not enabled yet</span></Aside></div>; }
function Field({ label, value, onChange, placeholder = "Optional", textarea }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; textarea?: boolean }) { return <div className="field"><label>{label}</label>{textarea ? <textarea className="textarea small" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /> : <input className="input" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} />}</div>; }
function ReviewStep({ setup, onBack }: { setup: Setup; onBack: () => void }) { return <div className="wizard-grid"><section className="card card-pad"><div className="eyebrow">Step 3 of 3</div><h2>Review & Go Live</h2><p className="subtitle">Review the draft before publishing. This screen establishes the future confirmation boundary.</p><div className="callout warning" style={{ margin: "22px 0" }}><span className="callout-icon">!</span><span>Publishing is intentionally conservative in Step 1. Review the draft here; AI and Meta integrations are not active.</span></div><div className="review-block"><h3>Page</h3><div className="review-value">{setup.pageName}</div></div><div className="review-block"><h3>Business information</h3><div className="review-value">{setup.rawBusinessInfo}</div></div><div className="grid grid-2"><Review label="Business name" value={setup.businessName || "Not set"} /><Review label="Benefits" value={setup.benefits || "Not set"} /><Review label="Delivery" value={setup.deliveryPolicy || "Not set"} /><Review label="COD" value={setup.codPolicy || "Not set"} /></div><div className="form-actions"><button className="button secondary" onClick={onBack}>Back to edit</button><Link className="button primary" href={`/pages/${setup.pageId}`}>Open page workspace →</Link></div></section><Aside title="Ready for review"><p>Draft configuration created successfully.</p><span className="status-chip amber"><span className="dot" /> Draft · not live</span><p>When publishing is enabled, the current draft will become live and the previous live version will be archived for rollback.</p></Aside></div>; }
function Review({ label, value }: { label: string; value: string }) { return <div className="review-block"><h3>{label}</h3><div className="review-value">{value}</div></div>; }
