"use client";

import { useEffect, useState } from "react";

type Budget = { monthlyBdt: number | null; dailyBdt: number | null; hardLimit: boolean; warningThreshold: number; modelOverride: "master" | "deepseek-v4-flash" | "deepseek-v4-pro"; pausedByBudget: boolean; usedBdt: number; remainingBdt: number | null; state: string; calls: number; inputTokens: number; outputTokens: number; estimatedUsd: number };

export function PageBudgetControl({ pageId }: { pageId: string }) {
  const [budget, setBudget] = useState<Budget | null>(null);
  const [monthly, setMonthly] = useState(""); const [daily, setDaily] = useState(""); const [hardLimit, setHardLimit] = useState(false); const [model, setModel] = useState<Budget["modelOverride"]>("master"); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
  async function load() { const response = await fetch(`/api/pages/${pageId}/budget`); const body = await response.json(); if (response.ok) { setBudget(body.budget); setMonthly(body.budget.monthlyBdt?.toString() ?? ""); setDaily(body.budget.dailyBdt?.toString() ?? ""); setHardLimit(body.budget.hardLimit); setModel(body.budget.modelOverride); } }
  useEffect(() => { void load(); }, [pageId]);
  async function save(action = "save") { setLoading(true); setNotice(""); const response = await fetch(`/api/pages/${pageId}/budget`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, monthlyBdt: monthly ? Number(monthly) : null, dailyBdt: daily ? Number(daily) : null, hardLimit, modelOverride: model }) }); const body = await response.json(); setLoading(false); if (!response.ok) { setNotice(body.error ?? "Unable to save budget."); return; } setBudget(body.budget); setNotice(action === "resume" ? "AI resumed for this Page." : action === "forceLimit" ? "Budget limit simulated." : "Page budget saved."); }
  return <section className="card card-pad" style={{ marginTop: 20 }}><div className="section-head inline-head"><div><h2>Cost control</h2><span className="muted">Internal Page budget · separate from provider balance.</span></div>{budget && <span className={`status-chip ${budget.state === "HEALTHY" ? "green" : budget.state === "PAUSED_BY_BUDGET" ? "gray" : "amber"}`}><span className="dot" />{budget.state.replaceAll("_", " ")}</span>}</div><div className="grid grid-4" style={{ marginTop: 18 }}><Metric label="This month" value={`৳${budget?.usedBdt.toFixed(2) ?? "0.00"}`} /><Metric label="Calls" value={String(budget?.calls ?? 0)} /><Metric label="Input tokens" value={(budget?.inputTokens ?? 0).toLocaleString()} /><Metric label="Output tokens" value={(budget?.outputTokens ?? 0).toLocaleString()} /></div><div className="form-grid" style={{ marginTop: 20 }}><Field label="Monthly budget BDT" value={monthly} onChange={setMonthly} /><Field label="Daily budget BDT" value={daily} onChange={setDaily} /><label className="field"><span>Model override</span><select className="input" value={model} onChange={(event) => setModel(event.target.value as Budget["modelOverride"])}><option value="master">Use Master</option><option value="deepseek-v4-flash">V4 Flash</option><option value="deepseek-v4-pro">V4 Pro</option></select></label><label className="setting-toggle"><span>Hard limit</span><button type="button" className={`toggle ${hardLimit ? "on" : ""}`} onClick={() => setHardLimit(!hardLimit)} aria-pressed={hardLimit} /></label></div><div className="form-actions"><button className="button primary" onClick={() => void save()} disabled={loading}>Save budget</button><button className="button secondary" onClick={() => void save("forceLimit")} disabled={loading}>Simulate limit</button>{budget?.pausedByBudget && <button className="button secondary" onClick={() => void save("resume")} disabled={loading}>Resume AI</button>}</div>{notice && <div className="callout info" role="status" style={{ marginTop: 12 }}>{notice}</div>}</section>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><input className="input" type="number" min="0" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><div className="metric-label">{label}</div><div className="metric-value" style={{ fontSize: 18 }}>{value}</div></div>; }
