"use client";

import { useState } from "react";
import { UnsavedChangesGuard } from "@/components/common/unsaved-changes-guard";

const defaults = ["name", "phone", "address", "product", "variant", "quantity"];
export function PageSettingsForm({ pageId, initial }: { pageId: string; initial: { currency: string; countryCode: string; defaultLanguage: string; tone: string; requiredOrderFields: string[] } }) {
  const [value, setValue] = useState(initial); const [baseline, setBaseline] = useState(initial); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const dirty = JSON.stringify(value) !== JSON.stringify(baseline);
  async function save() { setLoading(true); const response = await fetch(`/api/pages/${pageId}/settings`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value) }); const body = await response.json().catch(() => null); if (response.ok) { setBaseline(value); setMessage("Page settings saved."); } else setMessage(body?.error ?? "Unable to save settings."); setLoading(false); }
  function toggle(key: string) { setValue((current) => ({ ...current, requiredOrderFields: current.requiredOrderFields.includes(key) ? current.requiredOrderFields.filter((item) => item !== key) : [...current.requiredOrderFields, key] })); }
  return <div className="grid grid-2"><UnsavedChangesGuard dirty={dirty} /><section className="card card-pad"><h2>Page defaults</h2><p className="subtitle">These defaults are isolated to this Page.</p><div style={{ marginTop: 22 }}><div className="grid grid-2"><Field label="Currency" value={value.currency} onChange={(v) => setValue({ ...value, currency: v.toUpperCase() })} /><Field label="Country code" value={value.countryCode} onChange={(v) => setValue({ ...value, countryCode: v.toUpperCase() })} /></div><div className="grid grid-2"><Field label="Default language" value={value.defaultLanguage} onChange={(v) => setValue({ ...value, defaultLanguage: v })} /><Field label="Tone" value={value.tone} onChange={(v) => setValue({ ...value, tone: v })} /></div></div></section><section className="card card-pad"><h2>Required order fields</h2><p className="subtitle">These fields are checked by the backend before an order can be confirmed.</p><div style={{ display: "grid", gap: 9, margin: "22px 0" }}>{defaults.map((item) => <label key={item} style={{ display: "flex", gap: 10, alignItems: "center", color: "#46574f", fontSize: 12, fontWeight: 650 }}><input type="checkbox" checked={value.requiredOrderFields.includes(item)} onChange={() => toggle(item)} />{item.charAt(0).toUpperCase() + item.slice(1)}</label>)}</div>{message && <div className="callout info" style={{ marginBottom: 12 }} role="status">{message}</div>}<div className="form-actions"><button className="button primary" onClick={() => void save()} disabled={loading || !dirty || value.requiredOrderFields.length === 0}>{loading ? "Saving…" : "Save settings"}</button></div></section></div>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><input className="input" value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
