"use client";

import { useEffect, useState } from "react";

type Budget = { usdBdtRate: number; monthlyBdt: number | null; dailyBdt: number | null; hardLimit: boolean; warningThreshold: number; pausedByBudget: boolean; usedBdt: number; remainingBdt: number | null; state: string; calls: number; inputTokens: number; cachedInputTokens: number; outputTokens: number; estimatedUsd: number; costBdt: number };
export function PageBudgetControl({ pageId }: { pageId: string }) {
  const [budget, setBudget] = useState<Budget | null>(null); const [monthly, setMonthly] = useState(""); const [daily, setDaily] = useState(""); const [rate, setRate] = useState(""); const [warning, setWarning] = useState("85"); const [hardLimit, setHardLimit] = useState(false); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
  async function load() { const response = await fetch(`/api/pages/${pageId}/budget`); const body = await response.json(); if (response.ok) { setBudget(body.budget); setMonthly(body.budget.monthlyBdt?.toString() ?? ""); setDaily(body.budget.dailyBdt?.toString() ?? ""); setRate(body.budget.usdBdtRate?.toString() ?? "120"); setWarning(String(body.budget.warningThreshold ?? 85)); setHardLimit(body.budget.hardLimit); } }
  // The loader intentionally follows the selected Page ID.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [pageId]);
  async function save(action = "save") { setLoading(true); const response = await fetch(`/api/pages/${pageId}/budget`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, monthlyBdt: monthly ? Number(monthly) : null, dailyBdt: daily ? Number(daily) : null, usdBdtRate: rate ? Number(rate) : 120, hardLimit, warningThreshold: Number(warning) }) }); const body = await response.json(); setLoading(false); if (!response.ok) { setNotice(body.error ?? "Unable to save budget."); return; } setBudget(body.budget); setNotice(action === "resume" ? "AI resumed for this Page." : action === "forceLimit" ? "Page budget limit simulated." : "Page cost controls saved."); }
  return <section className="card card-pad" style={{ marginTop: 20 }}><div className="section-head inline-head"><div><h2>Cost control</h2><span className="muted">Internal Page budget is separate from provider balance.</span></div>{budget && <span className={`status-chip ${budget.state === "HEALTHY" ? "green" : budget.state === "PAUSED_BY_BUDGET" ? "gray" : "amber"}`}><span className="dot" />{budget.state.replaceAll("_", " ")}</span>}</div><div className="grid grid-4" style={{ marginTop: 18 }}><Metric label="Used BDT" value={`৳${budget?.usedBdt.toFixed(2) ?? "0.00"}`} /><Metric label="Remaining" value={budget?.remainingBdt === null ? "No cap" : `৳${budget?.remainingBdt.toFixed(2) ?? "0.00"}`} /><Metric label="Used USD" value={`$${budget?.estimatedUsd.toFixed(6) ?? "0.000000"}`} /><Metric label="Calls" value={String(budget?.calls ?? 0)} /></div><div className="form-grid" style={{ marginTop: 20 }}><Field label="USD → BDT rate" value={rate} onChange={setRate} /><Field label="Monthly budget BDT" value={monthly} onChange={setMonthly} /><Field label="Daily budget BDT" value={daily} onChange={setDaily} /><Field label="Warning threshold %" value={warning} onChange={setWarning} /><label className="setting-toggle"><span>Hard limit</span><button type="button" className={`toggle ${hardLimit ? "on" : ""}`} onClick={() => setHardLimit(!hardLimit)} aria-pressed={hardLimit} /></label></div><div className="form-actions"><button className="button primary" onClick={() => void save()} disabled={loading}>Save cost controls</button><button className="button secondary" onClick={() => void save("forceLimit")} disabled={loading}>Simulate limit</button>{budget?.pausedByBudget && <button className="button secondary" onClick={() => void save("resume")} disabled={loading}>Resume AI</button>}</div>{notice && <div className="callout info" role="status" style={{ marginTop: 12 }}>{notice}</div>}</section>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><input className="input" type="number" min="0" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><div className="metric-label">{label}</div><div className="metric-value" style={{ fontSize: 18 }}>{value}</div></div>; }
