"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export function ProductActions({ pageId, product }: { pageId: string; product: { id: string; name: string; description: string | null; active: boolean; variant: { sku: string; currentPrice: number; oldPrice: number | null; size: string | null; color: string | null } } }) {
  const router = useRouter(); const [editing, setEditing] = useState(false); const [confirming, setConfirming] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [name, setName] = useState(product.name); const [price, setPrice] = useState(String(product.variant.currentPrice));
  async function action(action: "activate" | "deactivate" | "delete") { setLoading(true); setError(""); const response = await fetch(`/api/products/${product.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageId, action }) }); const body = await response.json().catch(() => null); if (!response.ok) setError(body?.error ?? "Unable to update product."); else { setConfirming(false); router.refresh(); } setLoading(false); }
  async function save() { setLoading(true); setError(""); const response = await fetch(`/api/products/${product.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pageId, name, description: product.description ?? "", sku: product.variant.sku, price: Number(price), oldPrice: product.variant.oldPrice ?? undefined, size: product.variant.size ?? undefined, color: product.variant.color ?? undefined, active: product.active }) }); const body = await response.json().catch(() => null); if (!response.ok) setError(body?.error ?? "Unable to save product."); else { setEditing(false); router.refresh(); } setLoading(false); }
  return <div className="row-actions"><button className="text-button" onClick={() => setEditing(!editing)}>Edit</button><button className="text-button" onClick={() => void action(product.active ? "deactivate" : "activate")} disabled={loading}>{product.active ? "Deactivate" : "Activate"}</button><button className="text-button danger-text" onClick={() => setConfirming(true)}>Delete</button>{editing && <div className="inline-editor"><label>Name<input className="input" value={name} onChange={(e) => setName(e.target.value)} /></label><label>Price<input className="input" type="number" min="0.01" step="0.01" value={price} onChange={(e) => setPrice(e.target.value)} /></label><button className="button primary" onClick={() => void save()} disabled={loading}>Save</button></div>}{confirming && <div className="confirm-popover" role="dialog"><strong>Delete this product?</strong><span className="field-hint">This removes it from the preview catalog.</span><div><button className="button ghost" onClick={() => setConfirming(false)}>Cancel</button><button className="button danger" onClick={() => void action("delete")} disabled={loading}>{loading ? "Deleting…" : "Delete"}</button></div></div>}{error && <span className="field-hint" role="alert">{error}</span>}</div>;
}
