"use client";

import { useState } from "react";
import { UnsavedChangesGuard } from "@/components/common/unsaved-changes-guard";

type TelegramSettings = { tokenConfigured: boolean; accountLabel?: string; chatId: string; newOrderEnabled: boolean; updatedOrderEnabled: boolean; cancelledOrderEnabled: boolean; status: string };

export function TelegramSettingsPanel({ pageId, initial }: { pageId: string; initial: TelegramSettings }) {
  const [value, setValue] = useState(initial); const [baseline, setBaseline] = useState(initial); const [token, setToken] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false); const dirty = Boolean(token.trim()) || JSON.stringify(value) !== JSON.stringify(baseline);
  async function test() { setLoading(true); setNotice(""); const response = await fetch(`/api/pages/${pageId}/telegram`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "test", botToken: token || undefined, chatId: value.chatId, newOrderEnabled: value.newOrderEnabled, updatedOrderEnabled: value.updatedOrderEnabled, cancelledOrderEnabled: value.cancelledOrderEnabled }) }); const body = await response.json().catch(() => null); setLoading(false); if (!response.ok) { setNotice(body?.error ?? "Telegram test failed."); return; } setValue(body.settings); setNotice("Telegram test passed for this Page."); }
  async function save() { setLoading(true); setNotice(""); try { if (token.trim()) { const checked = await fetch(`/api/pages/${pageId}/telegram`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "test", botToken: token, chatId: value.chatId, newOrderEnabled: value.newOrderEnabled, updatedOrderEnabled: value.updatedOrderEnabled, cancelledOrderEnabled: value.cancelledOrderEnabled }) }); const checkedBody = await checked.json().catch(() => null); if (!checked.ok) throw new Error(checkedBody?.error ?? "Telegram test failed; the existing token was preserved."); } const response = await fetch(`/api/pages/${pageId}/telegram`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "save", botToken: token || undefined, chatId: value.chatId, newOrderEnabled: value.newOrderEnabled, updatedOrderEnabled: value.updatedOrderEnabled, cancelledOrderEnabled: value.cancelledOrderEnabled }) }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.error ?? "Unable to save Telegram settings."); setToken(""); setValue(body.settings); setBaseline(body.settings); setNotice("Telegram settings saved for this Page."); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save Telegram settings."); } finally { setLoading(false); } }
  return <div className="grid grid-2"><UnsavedChangesGuard dirty={dirty} /><section className="card card-pad"><div className="section-head inline-head"><div><h2>Telegram connection</h2><span className="muted">Only this Page can use this encrypted bot token.</span></div><span className={`status-chip ${value.status === "CONNECTED" ? "green" : value.status === "ERROR" ? "red" : "gray"}`}><span className="dot" />{value.status}</span></div><div className="locked-copy" style={{ marginTop: 18 }}>{value.accountLabel ?? "Page Telegram account"} · {value.tokenConfigured ? "Token configured · replace" : "Not configured"}</div><label className="field" style={{ marginTop: 18 }}><span>Bot Token</span><input className="input" type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder={value.tokenConfigured ? "Enter a replacement" : "Paste bot token"} autoComplete="new-password" /></label><label className="field"><span>Chat / Group ID</span><input className="input" value={value.chatId} onChange={(event) => setValue({ ...value, chatId: event.target.value })} /></label><div className="form-actions"><button className="button primary" onClick={() => void save()} disabled={loading || !dirty}>{loading ? "Saving…" : "Save Telegram"}</button><button className="button secondary" onClick={() => void test()} disabled={loading}>{loading ? "Testing…" : "Test Telegram"}</button></div>{notice && <div className="callout info" role="status" style={{ marginTop: 14 }}>{notice}</div>}</section><section className="card card-pad"><h2>Order notifications</h2><p className="subtitle">No global Telegram fallback exists. If this Page is not configured, only this Page is unavailable.</p><div className="locked-list" style={{ marginTop: 20 }}><Toggle label="NEW ORDER" value={value.newOrderEnabled} onChange={(next) => setValue({ ...value, newOrderEnabled: next })} /><Toggle label="UPDATED ORDER" value={value.updatedOrderEnabled} onChange={(next) => setValue({ ...value, updatedOrderEnabled: next })} /><Toggle label="CANCELLED ORDER" value={value.cancelledOrderEnabled} onChange={(next) => setValue({ ...value, cancelledOrderEnabled: next })} /></div></section></div>;
}
function Toggle({ label, value, onChange }: { label: string; value: boolean; onChange: (value: boolean) => void }) { return <div className="setting-toggle"><span>{label}</span><button type="button" className={`toggle ${value ? "on" : ""}`} onClick={() => onChange(!value)} aria-pressed={value} aria-label={`${label}: ${value ? "on" : "off"}`} /></div>; }
