"use client";

import Link from "next/link";
import { useState } from "react";
import type { PreviewControlCenter } from "@/services/preview/store";
import { SystemTestButton } from "@/components/settings/system-test-button";

type Section = "overview" | "meta" | "security" | "health";
export function ControlCenter({ initial, section = "overview" }: { initial: PreviewControlCenter | null; section?: Section }) {
  const [control, setControl] = useState(initial); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false); const [meta, setMeta] = useState({ appId: initial?.meta.appId ?? "", appSecret: "", verifyToken: "", graphApiVersion: initial?.meta.graphApiVersion ?? "v23.0" });
  async function action(payload: Record<string, unknown>) { setLoading(true); const response = await fetch("/api/settings/control-center", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => null); if (!response.ok) setNotice(body?.error ?? "Unable to save settings."); else { setControl(body.control); setNotice("Saved."); setMeta((value) => ({ ...value, appSecret: "", verifyToken: "" })); } setLoading(false); }
  if (!control) return <section className="card card-pad"><h2>Global Settings</h2><p className="subtitle">Global Settings contains only platform and operator infrastructure. AI, Telegram, and cost controls live inside each Page.</p></section>;
  return <div className="control-layout"><aside className="card control-nav"><div className="eyebrow">Super Admin</div><h2>Global Settings</h2><p className="subtitle">Only Meta remains a master integration.</p><nav>{([['overview', 'General'], ['meta', 'Meta Platform'], ['security', 'Security'], ['health', 'System Health']] as const).map(([key, label]) => <Link key={key} className={section === key ? "control-nav-link active" : "control-nav-link"} href={key === "overview" ? "/settings" : `/settings/${key}`}>{label}</Link>)}</nav></aside><div className="control-main">
    {section === "overview" && <><SectionHead title="General" description="Operator defaults and system-wide health only." /><div className="grid grid-3"><Metric title="Application" value={control.general.applicationName} /><Metric title="Currency" value={control.general.currency} /><Metric title="Timezone" value={control.general.timezone} /></div><section className="card card-pad" style={{ marginTop: 18 }}><div className="section-head inline-head"><div><h2>Global AI</h2><p className="subtitle">Pause stops new AI generation and sending across Pages; inbound messages remain stored.</p></div><span className={`status-chip ${control.globalAiPaused ? "amber" : "green"}`}><span className="dot" />{control.globalAiPaused ? "PAUSED" : "LIVE"}</span></div><button className={`button ${control.globalAiPaused ? "primary" : "secondary"}`} onClick={() => void action({ section: control.globalAiPaused ? "resumeAllAi" : "pauseAllAi" })} disabled={loading}>{loading ? "Updating…" : control.globalAiPaused ? "Resume All AI" : "Pause All AI"}</button></section><section className="card card-pad" style={{ marginTop: 18 }}><h2>Canonical URLs</h2><div className="url-list"><UrlRow label="Application" value={control.general.canonicalDomain} /><UrlRow label="OAuth callback" value={`${control.general.canonicalDomain}/api/meta/oauth/callback`} /><UrlRow label="Webhook" value={`${control.general.canonicalDomain}/api/meta/webhook`} /><UrlRow label="Privacy" value={`${control.general.canonicalDomain}/privacy`} /><UrlRow label="Data deletion" value={`${control.general.canonicalDomain}/data-deletion`} /></div></section><section className="card card-pad" style={{ marginTop: 18 }}><h2>Configuration ownership</h2><div className="locked-list"><span>Meta Platform · global master integration</span><span>AI · configured per Page</span><span>Telegram · configured per Page</span><span>AI cost and credit control · configured per Page</span></div></section></>}
    {section === "meta" && <><SectionHead title="Meta Platform" description="The single master Meta App used to connect Facebook Pages." /><form className="card card-pad form-grid" onSubmit={(event) => { event.preventDefault(); void action({ section: "meta", ...meta }); }}><Field label="App ID" value={meta.appId} onChange={(value) => setMeta({ ...meta, appId: value })} /><Field label="Graph API version" value={meta.graphApiVersion} onChange={(value) => setMeta({ ...meta, graphApiVersion: value })} /><SecretField label="App Secret" configured={control.meta.appSecretConfigured} value={meta.appSecret} onChange={(value) => setMeta({ ...meta, appSecret: value })} /><SecretField label="Webhook Verify Token" configured={control.meta.verifyTokenConfigured} value={meta.verifyToken} onChange={(value) => setMeta({ ...meta, verifyToken: value })} /><div className="form-actions"><button className="button primary" disabled={loading}>Save Meta Configuration</button><button type="button" className="button secondary" onClick={() => void action({ section: "testMeta" })} disabled={loading}>Test App Credentials</button><button type="button" className="button secondary" onClick={() => setNotice("OAuth callback and webhook diagnostics are available in System Health.")} disabled={loading}>Test OAuth</button></div></form><StatusPanel label="Platform status" status={control.meta.status} detail={control.meta.lastError ?? "Secrets are never returned after save."} /></>}
    {section === "security" && <><SectionHead title="Security" description="Encryption and operator safeguards." /><section className="card card-pad"><div className="locked-list"><span>Page AI and Telegram credentials are encrypted at rest.</span><span>Decrypted credentials never enter browser responses.</span><span>Every configuration mutation is page-scoped and audited.</span><span>Production preview mode is rejected.</span></div></section></>}
    {section === "health" && <><SectionHead title="System Health" description="System-wide infrastructure readiness." /><section className="card card-pad"><div className="integration-grid"><Integration name="App" status="Configured" /><Integration name="Database" status="Configured" /><Integration name="Worker" status="Configured" /><Integration name="Meta" status={control.meta.status} /></div><div style={{ marginTop: 18 }}><SystemTestButton /></div></section></>}
    {notice && <div className="callout info" role="status" style={{ marginTop: 16 }}>{notice}</div>}
  </div></div>;
}
function SectionHead({ title, description }: { title: string; description: string }) { return <div className="page-heading"><div><div className="eyebrow">Global Settings</div><h1>{title}</h1><p className="subtitle">{description}</p></div><span className="status-chip gray"><span className="dot" />Super Admin</span></div>; }
function Metric({ title, value }: { title: string; value: string }) { return <section className="card metric"><div className="metric-label">{title}</div><div className="metric-value" style={{ fontSize: 18 }}>{value}</div></section>; }
function Integration({ name, status }: { name: string; status: string }) { return <div className="integration-card"><strong>{name}</strong><span className="status-chip gray"><span className="dot" />{status}</span></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="field"><span>{label}</span><input className="input" value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function SecretField({ label, configured, value, onChange }: { label: string; configured: boolean; value: string; onChange: (value: string) => void }) { return <label className="field"><span>{label} <small>{configured ? "Configured · replace" : "Not configured"}</small></span><input className="input" type="password" value={value} onChange={(event) => onChange(event.target.value)} placeholder={configured ? "Enter a replacement" : "Paste secret"} autoComplete="new-password" /></label>; }
function StatusPanel({ label, status, detail }: { label: string; status: string; detail: string }) { return <section className="card card-pad" style={{ marginTop: 18 }}><div className="section-head inline-head"><h2>{label}</h2><span className="status-chip gray"><span className="dot" />{status}</span></div><p className="field-hint" style={{ marginTop: 14 }}>{detail}</p></section>; }
function UrlRow({ label, value }: { label: string; value: string }) { const [copied, setCopied] = useState(false); async function copy() { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1200); } return <div className="url-row"><span>{label}</span><code>{value}</code><button type="button" className="button secondary" onClick={() => void copy()}>{copied ? "Copied" : "Copy"}</button></div>; }
