import { NextResponse } from "next/server";
import { z } from "zod";
import { isSameOrigin } from "@/lib/auth/csrf";
import { requireAdmin } from "@/lib/auth/session";
import { isDevPreview } from "@/lib/env";
import { forcePreviewPageBudgetLimit, getPreviewBudgetSummary, resumePreviewPageAi, updatePreviewPageBudget } from "@/services/preview/store";

const schema = z.object({ useMasterSettings: z.boolean().optional(), monthlyBdt: z.number().nonnegative().nullable().optional(), dailyBdt: z.number().nonnegative().nullable().optional(), hardLimit: z.boolean().optional(), warningThreshold: z.number().int().min(1).max(100).optional(), maxOutputTokens: z.number().int().min(100).max(8000).nullable().optional(), modelOverride: z.enum(["master", "deepseek-v4-flash", "deepseek-v4-pro"]).optional(), action: z.enum(["save", "forceLimit", "resume"]).default("save") });
export async function GET(_request: Request, { params }: { params: Promise<{ pageId: string }> }) { await requireAdmin(); if (!isDevPreview()) return NextResponse.json({ error: "Page budget requires the configured database runtime." }, { status: 501 }); try { return NextResponse.json({ budget: getPreviewBudgetSummary((await params).pageId) }); } catch { return NextResponse.json({ error: "Page not found." }, { status: 404 }); } }
export async function POST(request: Request, { params }: { params: Promise<{ pageId: string }> }) { if (!isSameOrigin(request)) return NextResponse.json({ error: "Cross-site request rejected." }, { status: 403 }); await requireAdmin(); if (!isDevPreview()) return NextResponse.json({ error: "Page budget persistence requires the configured database runtime." }, { status: 501 }); const pageId = (await params).pageId; const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Check the Page budget fields." }, { status: 400 }); try { const budget = parsed.data.action === "forceLimit" ? forcePreviewPageBudgetLimit(pageId) : parsed.data.action === "resume" ? resumePreviewPageAi(pageId) : updatePreviewPageBudget(pageId, parsed.data); return NextResponse.json({ ok: true, budget }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Page not found." }, { status: 404 }); } }
