import { NextResponse } from "next/server";
import { z } from "zod";
import { isSameOrigin } from "@/lib/auth/csrf";
import { requireAdmin } from "@/lib/auth/session";
import { isDevPreview } from "@/lib/env";
import { prisma } from "@/lib/db/prisma";
import { forcePreviewPageBudgetLimit, getPreviewBudgetSummary, resumePreviewPageAi, updatePreviewPageBudget } from "@/services/preview/store";
import { startOfDhakaDay, startOfDhakaMonth } from "@/services/time/timezone";

const schema = z.object({ usdBdtRate: z.number().positive().optional(), monthlyBdt: z.number().nonnegative().nullable().optional(), dailyBdt: z.number().nonnegative().nullable().optional(), hardLimit: z.boolean().optional(), warningThreshold: z.number().int().min(1).max(100).optional(), action: z.enum(["save", "forceLimit", "resume"]).default("save") });
async function resolvePage(pageId: string) { return prisma.page.findFirst({ where: { OR: [{ id: pageId }, { slug: pageId }] }, select: { id: true } }); }
async function summary(pageId: string) { const settings = await prisma.pageCostSettings.findUnique({ where: { pageId } }); const [aggregate, daily] = await Promise.all([prisma.apiUsage.aggregate({ where: { pageId, createdAt: { gte: startOfDhakaMonth() } }, _count: { _all: true }, _sum: { inputTokens: true, cachedInputTokens: true, outputTokens: true, estimatedCostUsd: true, estimatedCostBdt: true } }), prisma.apiUsage.aggregate({ where: { pageId, createdAt: { gte: startOfDhakaDay() } }, _sum: { estimatedCostUsd: true, estimatedCostBdt: true } })]); const usedBdt = Number(aggregate._sum.estimatedCostBdt ?? 0); const dailyUsedBdt = Number(daily._sum.estimatedCostBdt ?? 0); const monthly = settings?.monthlyBudgetBdt === null || settings?.monthlyBudgetBdt === undefined ? null : Number(settings.monthlyBudgetBdt); const dailyLimit = settings?.dailyBudgetBdt === null || settings?.dailyBudgetBdt === undefined ? null : Number(settings.dailyBudgetBdt); const dailyExceeded = dailyLimit !== null && dailyUsedBdt >= dailyLimit; const monthlyExceeded = monthly !== null && usedBdt >= monthly; return { usdBdtRate: Number(settings?.usdBdtRate ?? 120), monthlyBdt: monthly, dailyBdt: dailyLimit, hardLimit: settings?.hardLimit ?? false, warningThreshold: settings?.warningThreshold ?? 85, pausedByBudget: settings?.pausedByBudget ?? false, reservedBdt: Number(settings?.reservedBdt ?? 0), usedBdt, dailyUsedBdt, remainingBdt: monthly === null ? null : Math.max(0, monthly - usedBdt), dailyRemainingBdt: dailyLimit === null ? null : Math.max(0, dailyLimit - dailyUsedBdt), state: settings?.pausedByBudget ? "PAUSED_BY_BUDGET" : dailyExceeded ? "LIMIT_REACHED_DAILY" : monthlyExceeded ? "LIMIT_REACHED_MONTHLY" : "HEALTHY", calls: aggregate._count._all, inputTokens: aggregate._sum.inputTokens ?? 0, cachedInputTokens: aggregate._sum.cachedInputTokens ?? 0, outputTokens: aggregate._sum.outputTokens ?? 0, estimatedUsd: Number(aggregate._sum.estimatedCostUsd ?? 0), dailyEstimatedUsd: Number(daily._sum.estimatedCostUsd ?? 0), costBdt: usedBdt }; }
export async function GET(_request: Request, { params }: { params: Promise<{ pageId: string }> }) { await requireAdmin(); const id = (await params).pageId; if (isDevPreview()) { try { return NextResponse.json({ budget: getPreviewBudgetSummary(id) }); } catch { return NextResponse.json({ error: "Page not found." }, { status: 404 }); } } const page = await resolvePage(id); if (!page) return NextResponse.json({ error: "Page not found." }, { status: 404 }); return NextResponse.json({ budget: await summary(page.id) }); }
export async function POST(request: Request, { params }: { params: Promise<{ pageId: string }> }) { if (!isSameOrigin(request)) return NextResponse.json({ error: "Cross-site request rejected." }, { status: 403 }); const admin = await requireAdmin(); const id = (await params).pageId; const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Check the Page cost controls." }, { status: 400 }); if (isDevPreview()) { try { const budget = parsed.data.action === "forceLimit" ? forcePreviewPageBudgetLimit(id) : parsed.data.action === "resume" ? resumePreviewPageAi(id) : updatePreviewPageBudget(id, parsed.data); return NextResponse.json({ ok: true, budget }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Page not found." }, { status: 404 }); } } const page = await resolvePage(id); if (!page) return NextResponse.json({ error: "Page not found." }, { status: 404 }); const { action, ...input } = parsed.data; if (action === "resume") { const settings = await prisma.pageCostSettings.findUnique({ where: { pageId: page.id } }); if (settings?.hardLimit) { const [month, day] = await Promise.all([prisma.apiUsage.aggregate({ where: { pageId: page.id, createdAt: { gte: startOfDhakaMonth() } }, _sum: { estimatedCostBdt: true } }), prisma.apiUsage.aggregate({ where: { pageId: page.id, createdAt: { gte: startOfDhakaDay() } }, _sum: { estimatedCostBdt: true } })]); const monthlyUsed = Number(month._sum.estimatedCostBdt ?? 0); const dailyUsed = Number(day._sum.estimatedCostBdt ?? 0); if ((settings.monthlyBudgetBdt !== null && monthlyUsed >= Number(settings.monthlyBudgetBdt)) || (settings.dailyBudgetBdt !== null && dailyUsed >= Number(settings.dailyBudgetBdt))) return NextResponse.json({ error: settings.dailyBudgetBdt !== null && dailyUsed >= Number(settings.dailyBudgetBdt) ? "AI cannot resume: the daily Page budget is still exceeded." : "AI cannot resume: the monthly Page budget is still exceeded." }, { status: 409 }); } } await prisma.$transaction(async (tx) => { if (action === "resume") { await tx.pageCostSettings.update({ where: { pageId: page.id }, data: { pausedByBudget: false } }); await tx.page.update({ where: { id: page.id }, data: { aiEnabled: true, aiStatus: "RUNNING" } }); } else { await tx.pageCostSettings.upsert({ where: { pageId: page.id }, update: input, create: { pageId: page.id, ...input } }); if (action === "forceLimit") await tx.page.update({ where: { id: page.id }, data: { aiEnabled: false, aiStatus: "PAUSED_BY_BUDGET" } }); } await tx.auditLog.create({ data: { adminId: admin.id, pageId: page.id, action: `ai.page_budget_${action}` } }); }); return NextResponse.json({ ok: true, budget: await summary(page.id) }); }
